<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common/finance.proto

namespace Eftypay\Common;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Address contains the address details for a buyer, seller or integrator.
 *
 * Generated from protobuf message <code>eftypay.common.Address</code>
 */
class Address extends \Google\Protobuf\Internal\Message
{
    /**
     * addressLine1 is the first address line.
     *
     * Generated from protobuf field <code>string addressLine1 = 1;</code>
     */
    protected $addressLine1 = '';
    /**
     * addressLine2 is the second address line.
     *
     * Generated from protobuf field <code>string addressLine2 = 2;</code>
     */
    protected $addressLine2 = '';
    /**
     * city contains the city name.
     *
     * Generated from protobuf field <code>string city = 3;</code>
     */
    protected $city = '';
    /**
     * stateOrCountry contains the state or county.
     *
     * Generated from protobuf field <code>string stateOrCounty = 4;</code>
     */
    protected $stateOrCounty = '';
    /**
     * postalCode contains the postal code.
     *
     * Generated from protobuf field <code>string postalCode = 5;</code>
     */
    protected $postalCode = '';
    /**
     * country contains the country name.
     *
     * Generated from protobuf field <code>.eftypay.common.CountryCode country = 6;</code>
     */
    protected $country = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $addressLine1
     *           addressLine1 is the first address line.
     *     @type string $addressLine2
     *           addressLine2 is the second address line.
     *     @type string $city
     *           city contains the city name.
     *     @type string $stateOrCounty
     *           stateOrCountry contains the state or county.
     *     @type string $postalCode
     *           postalCode contains the postal code.
     *     @type int $country
     *           country contains the country name.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Common\Finance::initOnce();
        parent::__construct($data);
    }

    /**
     * addressLine1 is the first address line.
     *
     * Generated from protobuf field <code>string addressLine1 = 1;</code>
     * @return string
     */
    public function getAddressLine1()
    {
        return $this->addressLine1;
    }

    /**
     * addressLine1 is the first address line.
     *
     * Generated from protobuf field <code>string addressLine1 = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setAddressLine1($var)
    {
        GPBUtil::checkString($var, True);
        $this->addressLine1 = $var;

        return $this;
    }

    /**
     * addressLine2 is the second address line.
     *
     * Generated from protobuf field <code>string addressLine2 = 2;</code>
     * @return string
     */
    public function getAddressLine2()
    {
        return $this->addressLine2;
    }

    /**
     * addressLine2 is the second address line.
     *
     * Generated from protobuf field <code>string addressLine2 = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setAddressLine2($var)
    {
        GPBUtil::checkString($var, True);
        $this->addressLine2 = $var;

        return $this;
    }

    /**
     * city contains the city name.
     *
     * Generated from protobuf field <code>string city = 3;</code>
     * @return string
     */
    public function getCity()
    {
        return $this->city;
    }

    /**
     * city contains the city name.
     *
     * Generated from protobuf field <code>string city = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setCity($var)
    {
        GPBUtil::checkString($var, True);
        $this->city = $var;

        return $this;
    }

    /**
     * stateOrCountry contains the state or county.
     *
     * Generated from protobuf field <code>string stateOrCounty = 4;</code>
     * @return string
     */
    public function getStateOrCounty()
    {
        return $this->stateOrCounty;
    }

    /**
     * stateOrCountry contains the state or county.
     *
     * Generated from protobuf field <code>string stateOrCounty = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setStateOrCounty($var)
    {
        GPBUtil::checkString($var, True);
        $this->stateOrCounty = $var;

        return $this;
    }

    /**
     * postalCode contains the postal code.
     *
     * Generated from protobuf field <code>string postalCode = 5;</code>
     * @return string
     */
    public function getPostalCode()
    {
        return $this->postalCode;
    }

    /**
     * postalCode contains the postal code.
     *
     * Generated from protobuf field <code>string postalCode = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setPostalCode($var)
    {
        GPBUtil::checkString($var, True);
        $this->postalCode = $var;

        return $this;
    }

    /**
     * country contains the country name.
     *
     * Generated from protobuf field <code>.eftypay.common.CountryCode country = 6;</code>
     * @return int
     */
    public function getCountry()
    {
        return $this->country;
    }

    /**
     * country contains the country name.
     *
     * Generated from protobuf field <code>.eftypay.common.CountryCode country = 6;</code>
     * @param int $var
     * @return $this
     */
    public function setCountry($var)
    {
        GPBUtil::checkEnum($var, \Eftypay\Common\CountryCode::class);
        $this->country = $var;

        return $this;
    }

}

