<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common/finance.proto

namespace Eftypay\Common;

use UnexpectedValueException;

/**
 * CountryCode holds the ISO country codes for all supported countries for buyers.
 *
 * Protobuf type <code>eftypay.common.CountryCode</code>
 */
class CountryCode
{
    /**
     * Generated from protobuf enum <code>COUNTRY_NONE = 0;</code>
     */
    const COUNTRY_NONE = 0;
    /**
     * Generated from protobuf enum <code>AF = 1;</code>
     */
    const AF = 1;
    /**
     * Generated from protobuf enum <code>AX = 2;</code>
     */
    const AX = 2;
    /**
     * Generated from protobuf enum <code>AL = 3;</code>
     */
    const AL = 3;
    /**
     * Generated from protobuf enum <code>DZ = 4;</code>
     */
    const DZ = 4;
    /**
     * Generated from protobuf enum <code>AS = 5;</code>
     */
    const PBAS = 5;
    /**
     * Generated from protobuf enum <code>AD = 6;</code>
     */
    const AD = 6;
    /**
     * Generated from protobuf enum <code>AO = 7;</code>
     */
    const AO = 7;
    /**
     * Generated from protobuf enum <code>AI = 8;</code>
     */
    const AI = 8;
    /**
     * Generated from protobuf enum <code>AQ = 9;</code>
     */
    const AQ = 9;
    /**
     * Generated from protobuf enum <code>AG = 10;</code>
     */
    const AG = 10;
    /**
     * Generated from protobuf enum <code>AR = 11;</code>
     */
    const AR = 11;
    /**
     * Generated from protobuf enum <code>AM = 12;</code>
     */
    const AM = 12;
    /**
     * Generated from protobuf enum <code>AW = 13;</code>
     */
    const AW = 13;
    /**
     * Generated from protobuf enum <code>AU = 14;</code>
     */
    const AU = 14;
    /**
     * Generated from protobuf enum <code>AT = 15;</code>
     */
    const AT = 15;
    /**
     * Generated from protobuf enum <code>AZ = 16;</code>
     */
    const AZ = 16;
    /**
     * Generated from protobuf enum <code>BS = 17;</code>
     */
    const BS = 17;
    /**
     * Generated from protobuf enum <code>BH = 18;</code>
     */
    const BH = 18;
    /**
     * Generated from protobuf enum <code>BD = 19;</code>
     */
    const BD = 19;
    /**
     * Generated from protobuf enum <code>BB = 20;</code>
     */
    const BB = 20;
    /**
     * Generated from protobuf enum <code>BY = 21;</code>
     */
    const BY = 21;
    /**
     * Generated from protobuf enum <code>BE = 22;</code>
     */
    const BE = 22;
    /**
     * Generated from protobuf enum <code>BZ = 23;</code>
     */
    const BZ = 23;
    /**
     * Generated from protobuf enum <code>BJ = 24;</code>
     */
    const BJ = 24;
    /**
     * Generated from protobuf enum <code>BM = 25;</code>
     */
    const BM = 25;
    /**
     * Generated from protobuf enum <code>BT = 26;</code>
     */
    const BT = 26;
    /**
     * Generated from protobuf enum <code>BO = 27;</code>
     */
    const BO = 27;
    /**
     * Generated from protobuf enum <code>BQ = 28;</code>
     */
    const BQ = 28;
    /**
     * Generated from protobuf enum <code>BA = 29;</code>
     */
    const BA = 29;
    /**
     * Generated from protobuf enum <code>BW = 30;</code>
     */
    const BW = 30;
    /**
     * Generated from protobuf enum <code>BV = 31;</code>
     */
    const BV = 31;
    /**
     * Generated from protobuf enum <code>BR = 32;</code>
     */
    const BR = 32;
    /**
     * Generated from protobuf enum <code>IO = 33;</code>
     */
    const IO = 33;
    /**
     * Generated from protobuf enum <code>BN = 34;</code>
     */
    const BN = 34;
    /**
     * Generated from protobuf enum <code>BG = 35;</code>
     */
    const BG = 35;
    /**
     * Generated from protobuf enum <code>BF = 36;</code>
     */
    const BF = 36;
    /**
     * Generated from protobuf enum <code>BI = 37;</code>
     */
    const BI = 37;
    /**
     * Generated from protobuf enum <code>KH = 38;</code>
     */
    const KH = 38;
    /**
     * Generated from protobuf enum <code>CM = 39;</code>
     */
    const CM = 39;
    /**
     * Generated from protobuf enum <code>CA = 40;</code>
     */
    const CA = 40;
    /**
     * Generated from protobuf enum <code>CV = 41;</code>
     */
    const CV = 41;
    /**
     * Generated from protobuf enum <code>KY = 42;</code>
     */
    const KY = 42;
    /**
     * Generated from protobuf enum <code>CF = 43;</code>
     */
    const CF = 43;
    /**
     * Generated from protobuf enum <code>TD = 44;</code>
     */
    const TD = 44;
    /**
     * Generated from protobuf enum <code>CL = 45;</code>
     */
    const CL = 45;
    /**
     * Generated from protobuf enum <code>CN = 46;</code>
     */
    const CN = 46;
    /**
     * Generated from protobuf enum <code>CX = 47;</code>
     */
    const CX = 47;
    /**
     * Generated from protobuf enum <code>CC = 48;</code>
     */
    const CC = 48;
    /**
     * Generated from protobuf enum <code>CO = 49;</code>
     */
    const CO = 49;
    /**
     * Generated from protobuf enum <code>KM = 50;</code>
     */
    const KM = 50;
    /**
     * Generated from protobuf enum <code>CG = 51;</code>
     */
    const CG = 51;
    /**
     * Generated from protobuf enum <code>CD = 52;</code>
     */
    const CD = 52;
    /**
     * Generated from protobuf enum <code>CK = 53;</code>
     */
    const CK = 53;
    /**
     * Generated from protobuf enum <code>CR = 54;</code>
     */
    const CR = 54;
    /**
     * Generated from protobuf enum <code>CI = 55;</code>
     */
    const CI = 55;
    /**
     * Generated from protobuf enum <code>HR = 56;</code>
     */
    const HR = 56;
    /**
     * Generated from protobuf enum <code>CU = 57;</code>
     */
    const CU = 57;
    /**
     * Generated from protobuf enum <code>CW = 58;</code>
     */
    const CW = 58;
    /**
     * Generated from protobuf enum <code>CY = 59;</code>
     */
    const CY = 59;
    /**
     * Generated from protobuf enum <code>CZ = 60;</code>
     */
    const CZ = 60;
    /**
     * Generated from protobuf enum <code>DK = 61;</code>
     */
    const DK = 61;
    /**
     * Generated from protobuf enum <code>DJ = 62;</code>
     */
    const DJ = 62;
    /**
     * Generated from protobuf enum <code>DM = 63;</code>
     */
    const DM = 63;
    /**
     * Generated from protobuf enum <code>DO = 64;</code>
     */
    const PBDO = 64;
    /**
     * Generated from protobuf enum <code>EC = 65;</code>
     */
    const EC = 65;
    /**
     * Generated from protobuf enum <code>EG = 66;</code>
     */
    const EG = 66;
    /**
     * Generated from protobuf enum <code>SV = 67;</code>
     */
    const SV = 67;
    /**
     * Generated from protobuf enum <code>GQ = 68;</code>
     */
    const GQ = 68;
    /**
     * Generated from protobuf enum <code>ER = 69;</code>
     */
    const ER = 69;
    /**
     * Generated from protobuf enum <code>EE = 70;</code>
     */
    const EE = 70;
    /**
     * Generated from protobuf enum <code>ET = 71;</code>
     */
    const ET = 71;
    /**
     * Generated from protobuf enum <code>FK = 72;</code>
     */
    const FK = 72;
    /**
     * Generated from protobuf enum <code>FO = 73;</code>
     */
    const FO = 73;
    /**
     * Generated from protobuf enum <code>FJ = 74;</code>
     */
    const FJ = 74;
    /**
     * Generated from protobuf enum <code>FI = 75;</code>
     */
    const FI = 75;
    /**
     * Generated from protobuf enum <code>FR = 76;</code>
     */
    const FR = 76;
    /**
     * Generated from protobuf enum <code>GF = 77;</code>
     */
    const GF = 77;
    /**
     * Generated from protobuf enum <code>PF = 78;</code>
     */
    const PF = 78;
    /**
     * Generated from protobuf enum <code>TF = 79;</code>
     */
    const TF = 79;
    /**
     * Generated from protobuf enum <code>GA = 80;</code>
     */
    const GA = 80;
    /**
     * Generated from protobuf enum <code>GM = 81;</code>
     */
    const GM = 81;
    /**
     * Generated from protobuf enum <code>GE = 82;</code>
     */
    const GE = 82;
    /**
     * Generated from protobuf enum <code>DE = 83;</code>
     */
    const DE = 83;
    /**
     * Generated from protobuf enum <code>GH = 84;</code>
     */
    const GH = 84;
    /**
     * Generated from protobuf enum <code>GI = 85;</code>
     */
    const GI = 85;
    /**
     * Generated from protobuf enum <code>GR = 86;</code>
     */
    const GR = 86;
    /**
     * Generated from protobuf enum <code>GL = 87;</code>
     */
    const GL = 87;
    /**
     * Generated from protobuf enum <code>GD = 88;</code>
     */
    const GD = 88;
    /**
     * Generated from protobuf enum <code>GP = 89;</code>
     */
    const GP = 89;
    /**
     * Generated from protobuf enum <code>GU = 90;</code>
     */
    const GU = 90;
    /**
     * Generated from protobuf enum <code>GT = 91;</code>
     */
    const GT = 91;
    /**
     * Generated from protobuf enum <code>GG = 92;</code>
     */
    const GG = 92;
    /**
     * Generated from protobuf enum <code>GN = 93;</code>
     */
    const GN = 93;
    /**
     * Generated from protobuf enum <code>GW = 94;</code>
     */
    const GW = 94;
    /**
     * Generated from protobuf enum <code>GY = 95;</code>
     */
    const GY = 95;
    /**
     * Generated from protobuf enum <code>HT = 96;</code>
     */
    const HT = 96;
    /**
     * Generated from protobuf enum <code>HM = 97;</code>
     */
    const HM = 97;
    /**
     * Generated from protobuf enum <code>VA = 98;</code>
     */
    const VA = 98;
    /**
     * Generated from protobuf enum <code>HN = 99;</code>
     */
    const HN = 99;
    /**
     * Generated from protobuf enum <code>HK = 100;</code>
     */
    const HK = 100;
    /**
     * Generated from protobuf enum <code>HU = 101;</code>
     */
    const HU = 101;
    /**
     * Generated from protobuf enum <code>IS = 102;</code>
     */
    const IS = 102;
    /**
     * Generated from protobuf enum <code>IN = 103;</code>
     */
    const IN = 103;
    /**
     * Generated from protobuf enum <code>ID = 104;</code>
     */
    const ID = 104;
    /**
     * Generated from protobuf enum <code>IR = 105;</code>
     */
    const IR = 105;
    /**
     * Generated from protobuf enum <code>IQ = 106;</code>
     */
    const IQ = 106;
    /**
     * Generated from protobuf enum <code>IE = 107;</code>
     */
    const IE = 107;
    /**
     * Generated from protobuf enum <code>IM = 108;</code>
     */
    const IM = 108;
    /**
     * Generated from protobuf enum <code>IL = 109;</code>
     */
    const IL = 109;
    /**
     * Generated from protobuf enum <code>IT = 110;</code>
     */
    const IT = 110;
    /**
     * Generated from protobuf enum <code>JM = 111;</code>
     */
    const JM = 111;
    /**
     * Generated from protobuf enum <code>JP = 112;</code>
     */
    const JP = 112;
    /**
     * Generated from protobuf enum <code>JE = 113;</code>
     */
    const JE = 113;
    /**
     * Generated from protobuf enum <code>JO = 114;</code>
     */
    const JO = 114;
    /**
     * Generated from protobuf enum <code>KZ = 115;</code>
     */
    const KZ = 115;
    /**
     * Generated from protobuf enum <code>KE = 116;</code>
     */
    const KE = 116;
    /**
     * Generated from protobuf enum <code>KI = 117;</code>
     */
    const KI = 117;
    /**
     * Generated from protobuf enum <code>KP = 118;</code>
     */
    const KP = 118;
    /**
     * Generated from protobuf enum <code>KR = 119;</code>
     */
    const KR = 119;
    /**
     * Generated from protobuf enum <code>KW = 120;</code>
     */
    const KW = 120;
    /**
     * Generated from protobuf enum <code>KG = 121;</code>
     */
    const KG = 121;
    /**
     * Generated from protobuf enum <code>LA = 122;</code>
     */
    const LA = 122;
    /**
     * Generated from protobuf enum <code>LV = 123;</code>
     */
    const LV = 123;
    /**
     * Generated from protobuf enum <code>LB = 124;</code>
     */
    const LB = 124;
    /**
     * Generated from protobuf enum <code>LS = 125;</code>
     */
    const LS = 125;
    /**
     * Generated from protobuf enum <code>LR = 126;</code>
     */
    const LR = 126;
    /**
     * Generated from protobuf enum <code>LY = 127;</code>
     */
    const LY = 127;
    /**
     * Generated from protobuf enum <code>LI = 128;</code>
     */
    const LI = 128;
    /**
     * Generated from protobuf enum <code>LT = 129;</code>
     */
    const LT = 129;
    /**
     * Generated from protobuf enum <code>LU = 130;</code>
     */
    const LU = 130;
    /**
     * Generated from protobuf enum <code>MO = 131;</code>
     */
    const MO = 131;
    /**
     * Generated from protobuf enum <code>MK = 132;</code>
     */
    const MK = 132;
    /**
     * Generated from protobuf enum <code>MG = 133;</code>
     */
    const MG = 133;
    /**
     * Generated from protobuf enum <code>MW = 134;</code>
     */
    const MW = 134;
    /**
     * Generated from protobuf enum <code>MY = 135;</code>
     */
    const MY = 135;
    /**
     * Generated from protobuf enum <code>MV = 136;</code>
     */
    const MV = 136;
    /**
     * Generated from protobuf enum <code>ML = 137;</code>
     */
    const ML = 137;
    /**
     * Generated from protobuf enum <code>MT = 138;</code>
     */
    const MT = 138;
    /**
     * Generated from protobuf enum <code>MH = 139;</code>
     */
    const MH = 139;
    /**
     * Generated from protobuf enum <code>MQ = 140;</code>
     */
    const MQ = 140;
    /**
     * Generated from protobuf enum <code>MR = 141;</code>
     */
    const MR = 141;
    /**
     * Generated from protobuf enum <code>MU = 142;</code>
     */
    const MU = 142;
    /**
     * Generated from protobuf enum <code>YT = 143;</code>
     */
    const YT = 143;
    /**
     * Generated from protobuf enum <code>MX = 144;</code>
     */
    const MX = 144;
    /**
     * Generated from protobuf enum <code>FM = 145;</code>
     */
    const FM = 145;
    /**
     * Generated from protobuf enum <code>MD = 146;</code>
     */
    const MD = 146;
    /**
     * Generated from protobuf enum <code>MC = 147;</code>
     */
    const MC = 147;
    /**
     * Generated from protobuf enum <code>MN = 148;</code>
     */
    const MN = 148;
    /**
     * Generated from protobuf enum <code>ME = 149;</code>
     */
    const ME = 149;
    /**
     * Generated from protobuf enum <code>MS = 150;</code>
     */
    const MS = 150;
    /**
     * Generated from protobuf enum <code>MA = 151;</code>
     */
    const MA = 151;
    /**
     * Generated from protobuf enum <code>MZ = 152;</code>
     */
    const MZ = 152;
    /**
     * Generated from protobuf enum <code>MM = 153;</code>
     */
    const MM = 153;
    /**
     * Generated from protobuf enum <code>NA = 154;</code>
     */
    const NA = 154;
    /**
     * Generated from protobuf enum <code>NR = 155;</code>
     */
    const NR = 155;
    /**
     * Generated from protobuf enum <code>NP = 156;</code>
     */
    const NP = 156;
    /**
     * Generated from protobuf enum <code>NL = 157;</code>
     */
    const NL = 157;
    /**
     * Generated from protobuf enum <code>NC = 158;</code>
     */
    const NC = 158;
    /**
     * Generated from protobuf enum <code>NZ = 159;</code>
     */
    const NZ = 159;
    /**
     * Generated from protobuf enum <code>NI = 160;</code>
     */
    const NI = 160;
    /**
     * Generated from protobuf enum <code>NE = 161;</code>
     */
    const NE = 161;
    /**
     * Generated from protobuf enum <code>NG = 162;</code>
     */
    const NG = 162;
    /**
     * Generated from protobuf enum <code>NU = 163;</code>
     */
    const NU = 163;
    /**
     * Generated from protobuf enum <code>NF = 164;</code>
     */
    const NF = 164;
    /**
     * Generated from protobuf enum <code>MP = 165;</code>
     */
    const MP = 165;
    /**
     * Generated from protobuf enum <code>NO = 166;</code>
     */
    const NO = 166;
    /**
     * Generated from protobuf enum <code>OM = 167;</code>
     */
    const OM = 167;
    /**
     * Generated from protobuf enum <code>PK = 168;</code>
     */
    const PK = 168;
    /**
     * Generated from protobuf enum <code>PW = 169;</code>
     */
    const PW = 169;
    /**
     * Generated from protobuf enum <code>PS = 170;</code>
     */
    const PS = 170;
    /**
     * Generated from protobuf enum <code>PA = 171;</code>
     */
    const PA = 171;
    /**
     * Generated from protobuf enum <code>PG = 172;</code>
     */
    const PG = 172;
    /**
     * Generated from protobuf enum <code>PY = 173;</code>
     */
    const PY = 173;
    /**
     * Generated from protobuf enum <code>PE = 174;</code>
     */
    const PE = 174;
    /**
     * Generated from protobuf enum <code>PH = 175;</code>
     */
    const PH = 175;
    /**
     * Generated from protobuf enum <code>PN = 176;</code>
     */
    const PN = 176;
    /**
     * Generated from protobuf enum <code>PL = 177;</code>
     */
    const PL = 177;
    /**
     * Generated from protobuf enum <code>PT = 178;</code>
     */
    const PT = 178;
    /**
     * Generated from protobuf enum <code>PR = 179;</code>
     */
    const PR = 179;
    /**
     * Generated from protobuf enum <code>QA = 180;</code>
     */
    const QA = 180;
    /**
     * Generated from protobuf enum <code>RE = 181;</code>
     */
    const RE = 181;
    /**
     * Generated from protobuf enum <code>RO = 182;</code>
     */
    const RO = 182;
    /**
     * Generated from protobuf enum <code>RU = 183;</code>
     */
    const RU = 183;
    /**
     * Generated from protobuf enum <code>RW = 184;</code>
     */
    const RW = 184;
    /**
     * Generated from protobuf enum <code>BL = 185;</code>
     */
    const BL = 185;
    /**
     * Generated from protobuf enum <code>SH = 186;</code>
     */
    const SH = 186;
    /**
     * Generated from protobuf enum <code>KN = 187;</code>
     */
    const KN = 187;
    /**
     * Generated from protobuf enum <code>LC = 188;</code>
     */
    const LC = 188;
    /**
     * Generated from protobuf enum <code>MF = 189;</code>
     */
    const MF = 189;
    /**
     * Generated from protobuf enum <code>PM = 190;</code>
     */
    const PM = 190;
    /**
     * Generated from protobuf enum <code>VC = 191;</code>
     */
    const VC = 191;
    /**
     * Generated from protobuf enum <code>WS = 192;</code>
     */
    const WS = 192;
    /**
     * Generated from protobuf enum <code>SM = 193;</code>
     */
    const SM = 193;
    /**
     * Generated from protobuf enum <code>ST = 194;</code>
     */
    const ST = 194;
    /**
     * Generated from protobuf enum <code>SA = 195;</code>
     */
    const SA = 195;
    /**
     * Generated from protobuf enum <code>SN = 196;</code>
     */
    const SN = 196;
    /**
     * Generated from protobuf enum <code>RS = 197;</code>
     */
    const RS = 197;
    /**
     * Generated from protobuf enum <code>SC = 198;</code>
     */
    const SC = 198;
    /**
     * Generated from protobuf enum <code>SL = 199;</code>
     */
    const SL = 199;
    /**
     * Generated from protobuf enum <code>SG = 200;</code>
     */
    const SG = 200;
    /**
     * Generated from protobuf enum <code>SX = 201;</code>
     */
    const SX = 201;
    /**
     * Generated from protobuf enum <code>SK = 202;</code>
     */
    const SK = 202;
    /**
     * Generated from protobuf enum <code>SI = 203;</code>
     */
    const SI = 203;
    /**
     * Generated from protobuf enum <code>SB = 204;</code>
     */
    const SB = 204;
    /**
     * Generated from protobuf enum <code>SO = 205;</code>
     */
    const SO = 205;
    /**
     * Generated from protobuf enum <code>ZA = 206;</code>
     */
    const ZA = 206;
    /**
     * Generated from protobuf enum <code>GS = 207;</code>
     */
    const GS = 207;
    /**
     * Generated from protobuf enum <code>SS = 208;</code>
     */
    const SS = 208;
    /**
     * Generated from protobuf enum <code>ES = 209;</code>
     */
    const ES = 209;
    /**
     * Generated from protobuf enum <code>LK = 210;</code>
     */
    const LK = 210;
    /**
     * Generated from protobuf enum <code>SD = 211;</code>
     */
    const SD = 211;
    /**
     * Generated from protobuf enum <code>SR = 212;</code>
     */
    const SR = 212;
    /**
     * Generated from protobuf enum <code>SJ = 213;</code>
     */
    const SJ = 213;
    /**
     * Generated from protobuf enum <code>SZ = 214;</code>
     */
    const SZ = 214;
    /**
     * Generated from protobuf enum <code>SE = 215;</code>
     */
    const SE = 215;
    /**
     * Generated from protobuf enum <code>CH = 216;</code>
     */
    const CH = 216;
    /**
     * Generated from protobuf enum <code>SY = 217;</code>
     */
    const SY = 217;
    /**
     * Generated from protobuf enum <code>TW = 218;</code>
     */
    const TW = 218;
    /**
     * Generated from protobuf enum <code>TJ = 219;</code>
     */
    const TJ = 219;
    /**
     * Generated from protobuf enum <code>TZ = 220;</code>
     */
    const TZ = 220;
    /**
     * Generated from protobuf enum <code>TH = 221;</code>
     */
    const TH = 221;
    /**
     * Generated from protobuf enum <code>TL = 222;</code>
     */
    const TL = 222;
    /**
     * Generated from protobuf enum <code>TG = 223;</code>
     */
    const TG = 223;
    /**
     * Generated from protobuf enum <code>TK = 224;</code>
     */
    const TK = 224;
    /**
     * Generated from protobuf enum <code>TO = 225;</code>
     */
    const TO = 225;
    /**
     * Generated from protobuf enum <code>TT = 226;</code>
     */
    const TT = 226;
    /**
     * Generated from protobuf enum <code>TN = 227;</code>
     */
    const TN = 227;
    /**
     * Generated from protobuf enum <code>TR = 228;</code>
     */
    const TR = 228;
    /**
     * Generated from protobuf enum <code>TM = 229;</code>
     */
    const TM = 229;
    /**
     * Generated from protobuf enum <code>TC = 230;</code>
     */
    const TC = 230;
    /**
     * Generated from protobuf enum <code>TV = 231;</code>
     */
    const TV = 231;
    /**
     * Generated from protobuf enum <code>UG = 232;</code>
     */
    const UG = 232;
    /**
     * Generated from protobuf enum <code>UA = 233;</code>
     */
    const UA = 233;
    /**
     * Generated from protobuf enum <code>AE = 234;</code>
     */
    const AE = 234;
    /**
     * Generated from protobuf enum <code>GB = 235;</code>
     */
    const GB = 235;
    /**
     * Generated from protobuf enum <code>US = 236;</code>
     */
    const US = 236;
    /**
     * Generated from protobuf enum <code>UM = 237;</code>
     */
    const UM = 237;
    /**
     * Generated from protobuf enum <code>UY = 238;</code>
     */
    const UY = 238;
    /**
     * Generated from protobuf enum <code>UZ = 239;</code>
     */
    const UZ = 239;
    /**
     * Generated from protobuf enum <code>VU = 240;</code>
     */
    const VU = 240;
    /**
     * Generated from protobuf enum <code>VE = 241;</code>
     */
    const VE = 241;
    /**
     * Generated from protobuf enum <code>VN = 242;</code>
     */
    const VN = 242;
    /**
     * Generated from protobuf enum <code>VG = 243;</code>
     */
    const VG = 243;
    /**
     * Generated from protobuf enum <code>VI = 244;</code>
     */
    const VI = 244;
    /**
     * Generated from protobuf enum <code>WF = 245;</code>
     */
    const WF = 245;
    /**
     * Generated from protobuf enum <code>EH = 246;</code>
     */
    const EH = 246;
    /**
     * Generated from protobuf enum <code>YE = 247;</code>
     */
    const YE = 247;
    /**
     * Generated from protobuf enum <code>ZM = 248;</code>
     */
    const ZM = 248;
    /**
     * Generated from protobuf enum <code>ZW = 249;</code>
     */
    const ZW = 249;

    private static $valueToName = [
        self::COUNTRY_NONE => 'COUNTRY_NONE',
        self::AF => 'AF',
        self::AX => 'AX',
        self::AL => 'AL',
        self::DZ => 'DZ',
        self::PBAS => 'AS',
        self::AD => 'AD',
        self::AO => 'AO',
        self::AI => 'AI',
        self::AQ => 'AQ',
        self::AG => 'AG',
        self::AR => 'AR',
        self::AM => 'AM',
        self::AW => 'AW',
        self::AU => 'AU',
        self::AT => 'AT',
        self::AZ => 'AZ',
        self::BS => 'BS',
        self::BH => 'BH',
        self::BD => 'BD',
        self::BB => 'BB',
        self::BY => 'BY',
        self::BE => 'BE',
        self::BZ => 'BZ',
        self::BJ => 'BJ',
        self::BM => 'BM',
        self::BT => 'BT',
        self::BO => 'BO',
        self::BQ => 'BQ',
        self::BA => 'BA',
        self::BW => 'BW',
        self::BV => 'BV',
        self::BR => 'BR',
        self::IO => 'IO',
        self::BN => 'BN',
        self::BG => 'BG',
        self::BF => 'BF',
        self::BI => 'BI',
        self::KH => 'KH',
        self::CM => 'CM',
        self::CA => 'CA',
        self::CV => 'CV',
        self::KY => 'KY',
        self::CF => 'CF',
        self::TD => 'TD',
        self::CL => 'CL',
        self::CN => 'CN',
        self::CX => 'CX',
        self::CC => 'CC',
        self::CO => 'CO',
        self::KM => 'KM',
        self::CG => 'CG',
        self::CD => 'CD',
        self::CK => 'CK',
        self::CR => 'CR',
        self::CI => 'CI',
        self::HR => 'HR',
        self::CU => 'CU',
        self::CW => 'CW',
        self::CY => 'CY',
        self::CZ => 'CZ',
        self::DK => 'DK',
        self::DJ => 'DJ',
        self::DM => 'DM',
        self::PBDO => 'DO',
        self::EC => 'EC',
        self::EG => 'EG',
        self::SV => 'SV',
        self::GQ => 'GQ',
        self::ER => 'ER',
        self::EE => 'EE',
        self::ET => 'ET',
        self::FK => 'FK',
        self::FO => 'FO',
        self::FJ => 'FJ',
        self::FI => 'FI',
        self::FR => 'FR',
        self::GF => 'GF',
        self::PF => 'PF',
        self::TF => 'TF',
        self::GA => 'GA',
        self::GM => 'GM',
        self::GE => 'GE',
        self::DE => 'DE',
        self::GH => 'GH',
        self::GI => 'GI',
        self::GR => 'GR',
        self::GL => 'GL',
        self::GD => 'GD',
        self::GP => 'GP',
        self::GU => 'GU',
        self::GT => 'GT',
        self::GG => 'GG',
        self::GN => 'GN',
        self::GW => 'GW',
        self::GY => 'GY',
        self::HT => 'HT',
        self::HM => 'HM',
        self::VA => 'VA',
        self::HN => 'HN',
        self::HK => 'HK',
        self::HU => 'HU',
        self::IS => 'IS',
        self::IN => 'IN',
        self::ID => 'ID',
        self::IR => 'IR',
        self::IQ => 'IQ',
        self::IE => 'IE',
        self::IM => 'IM',
        self::IL => 'IL',
        self::IT => 'IT',
        self::JM => 'JM',
        self::JP => 'JP',
        self::JE => 'JE',
        self::JO => 'JO',
        self::KZ => 'KZ',
        self::KE => 'KE',
        self::KI => 'KI',
        self::KP => 'KP',
        self::KR => 'KR',
        self::KW => 'KW',
        self::KG => 'KG',
        self::LA => 'LA',
        self::LV => 'LV',
        self::LB => 'LB',
        self::LS => 'LS',
        self::LR => 'LR',
        self::LY => 'LY',
        self::LI => 'LI',
        self::LT => 'LT',
        self::LU => 'LU',
        self::MO => 'MO',
        self::MK => 'MK',
        self::MG => 'MG',
        self::MW => 'MW',
        self::MY => 'MY',
        self::MV => 'MV',
        self::ML => 'ML',
        self::MT => 'MT',
        self::MH => 'MH',
        self::MQ => 'MQ',
        self::MR => 'MR',
        self::MU => 'MU',
        self::YT => 'YT',
        self::MX => 'MX',
        self::FM => 'FM',
        self::MD => 'MD',
        self::MC => 'MC',
        self::MN => 'MN',
        self::ME => 'ME',
        self::MS => 'MS',
        self::MA => 'MA',
        self::MZ => 'MZ',
        self::MM => 'MM',
        self::NA => 'NA',
        self::NR => 'NR',
        self::NP => 'NP',
        self::NL => 'NL',
        self::NC => 'NC',
        self::NZ => 'NZ',
        self::NI => 'NI',
        self::NE => 'NE',
        self::NG => 'NG',
        self::NU => 'NU',
        self::NF => 'NF',
        self::MP => 'MP',
        self::NO => 'NO',
        self::OM => 'OM',
        self::PK => 'PK',
        self::PW => 'PW',
        self::PS => 'PS',
        self::PA => 'PA',
        self::PG => 'PG',
        self::PY => 'PY',
        self::PE => 'PE',
        self::PH => 'PH',
        self::PN => 'PN',
        self::PL => 'PL',
        self::PT => 'PT',
        self::PR => 'PR',
        self::QA => 'QA',
        self::RE => 'RE',
        self::RO => 'RO',
        self::RU => 'RU',
        self::RW => 'RW',
        self::BL => 'BL',
        self::SH => 'SH',
        self::KN => 'KN',
        self::LC => 'LC',
        self::MF => 'MF',
        self::PM => 'PM',
        self::VC => 'VC',
        self::WS => 'WS',
        self::SM => 'SM',
        self::ST => 'ST',
        self::SA => 'SA',
        self::SN => 'SN',
        self::RS => 'RS',
        self::SC => 'SC',
        self::SL => 'SL',
        self::SG => 'SG',
        self::SX => 'SX',
        self::SK => 'SK',
        self::SI => 'SI',
        self::SB => 'SB',
        self::SO => 'SO',
        self::ZA => 'ZA',
        self::GS => 'GS',
        self::SS => 'SS',
        self::ES => 'ES',
        self::LK => 'LK',
        self::SD => 'SD',
        self::SR => 'SR',
        self::SJ => 'SJ',
        self::SZ => 'SZ',
        self::SE => 'SE',
        self::CH => 'CH',
        self::SY => 'SY',
        self::TW => 'TW',
        self::TJ => 'TJ',
        self::TZ => 'TZ',
        self::TH => 'TH',
        self::TL => 'TL',
        self::TG => 'TG',
        self::TK => 'TK',
        self::TO => 'TO',
        self::TT => 'TT',
        self::TN => 'TN',
        self::TR => 'TR',
        self::TM => 'TM',
        self::TC => 'TC',
        self::TV => 'TV',
        self::UG => 'UG',
        self::UA => 'UA',
        self::AE => 'AE',
        self::GB => 'GB',
        self::US => 'US',
        self::UM => 'UM',
        self::UY => 'UY',
        self::UZ => 'UZ',
        self::VU => 'VU',
        self::VE => 'VE',
        self::VN => 'VN',
        self::VG => 'VG',
        self::VI => 'VI',
        self::WF => 'WF',
        self::EH => 'EH',
        self::YE => 'YE',
        self::ZM => 'ZM',
        self::ZW => 'ZW',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            $pbconst =  __CLASS__. '::PB' . strtoupper($name);
            if (!defined($pbconst)) {
                throw new UnexpectedValueException(sprintf(
                        'Enum %s has no value defined for name %s', __CLASS__, $name));
            }
            return constant($pbconst);
        }
        return constant($const);
    }
}

