<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common/common.proto

namespace Eftypay\Common;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * GetObjectRequest is used to get individual objects by indexed fields (for example, get a Party by email)
 *
 * Generated from protobuf message <code>eftypay.common.GetObjectRequest</code>
 */
class GetObjectRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * fieldValue indicates the value of the indexed field. Which field this value is compared to is handled by implementation / endpoint.
     *
     * Generated from protobuf field <code>string fieldValue = 1;</code>
     */
    protected $fieldValue = '';
    /**
     * integratorId is an optional field to indicate the integrator data-space. Can only be set by admin.
     *
     * Generated from protobuf field <code>string integratorId = 2;</code>
     */
    protected $integratorId = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $fieldValue
     *           fieldValue indicates the value of the indexed field. Which field this value is compared to is handled by implementation / endpoint.
     *     @type string $integratorId
     *           integratorId is an optional field to indicate the integrator data-space. Can only be set by admin.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Common\Common::initOnce();
        parent::__construct($data);
    }

    /**
     * fieldValue indicates the value of the indexed field. Which field this value is compared to is handled by implementation / endpoint.
     *
     * Generated from protobuf field <code>string fieldValue = 1;</code>
     * @return string
     */
    public function getFieldValue()
    {
        return $this->fieldValue;
    }

    /**
     * fieldValue indicates the value of the indexed field. Which field this value is compared to is handled by implementation / endpoint.
     *
     * Generated from protobuf field <code>string fieldValue = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setFieldValue($var)
    {
        GPBUtil::checkString($var, True);
        $this->fieldValue = $var;

        return $this;
    }

    /**
     * integratorId is an optional field to indicate the integrator data-space. Can only be set by admin.
     *
     * Generated from protobuf field <code>string integratorId = 2;</code>
     * @return string
     */
    public function getIntegratorId()
    {
        return $this->integratorId;
    }

    /**
     * integratorId is an optional field to indicate the integrator data-space. Can only be set by admin.
     *
     * Generated from protobuf field <code>string integratorId = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setIntegratorId($var)
    {
        GPBUtil::checkString($var, True);
        $this->integratorId = $var;

        return $this;
    }

}

