<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common/common.proto

namespace Eftypay\Common;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Id object for requesting objects by individual ID's.
 *
 * Generated from protobuf message <code>eftypay.common.Id</code>
 */
class Id extends \Google\Protobuf\Internal\Message
{
    /**
     * id is the ID of the object that is being requested.
     *
     * Generated from protobuf field <code>string id = 1;</code>
     */
    protected $id = '';
    /**
     * integratorId is an optional field to indicate the integrator data-space. Can only be set by admin.
     *
     * Generated from protobuf field <code>string integratorId = 2;</code>
     */
    protected $integratorId = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $id
     *           id is the ID of the object that is being requested.
     *     @type string $integratorId
     *           integratorId is an optional field to indicate the integrator data-space. Can only be set by admin.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Common\Common::initOnce();
        parent::__construct($data);
    }

    /**
     * id is the ID of the object that is being requested.
     *
     * Generated from protobuf field <code>string id = 1;</code>
     * @return string
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * id is the ID of the object that is being requested.
     *
     * Generated from protobuf field <code>string id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkString($var, True);
        $this->id = $var;

        return $this;
    }

    /**
     * integratorId is an optional field to indicate the integrator data-space. Can only be set by admin.
     *
     * Generated from protobuf field <code>string integratorId = 2;</code>
     * @return string
     */
    public function getIntegratorId()
    {
        return $this->integratorId;
    }

    /**
     * integratorId is an optional field to indicate the integrator data-space. Can only be set by admin.
     *
     * Generated from protobuf field <code>string integratorId = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setIntegratorId($var)
    {
        GPBUtil::checkString($var, True);
        $this->integratorId = $var;

        return $this;
    }

}

