<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common/common.proto

namespace Eftypay\Common;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * ListRequest is used to narrow down the results returned from any of the list endpoints.
 *
 * Generated from protobuf message <code>eftypay.common.ListRequest</code>
 */
class ListRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * limit is the number of results to return in the response. The backend allows a max value of 100 for this field (which is also what it defaults to).
     *
     * Generated from protobuf field <code>int32 limit = 1;</code>
     */
    protected $limit = 0;
    /**
     * startAfter indicates where in the record set the search should start. Pass in the last document ID from the previous result to start from here.
     *
     * Generated from protobuf field <code>string startAfter = 2;</code>
     */
    protected $startAfter = '';
    /**
     * queries contains the query conditions applied in the list search.
     *
     * Generated from protobuf field <code>repeated .eftypay.common.Query queries = 3;</code>
     */
    private $queries;
    /**
     * orderByField set on which fields the resultset is ordered. Defaults to the created date in most cases.
     *
     * Generated from protobuf field <code>string orderByField = 4;</code>
     */
    protected $orderByField = '';
    /**
     * order sets the order direction.
     *
     * Generated from protobuf field <code>.eftypay.common.OrderDirection order = 5;</code>
     */
    protected $order = 0;
    /**
     * integratorId is an optional field to indicate the integrator data-space. Can only be set by admin.
     *
     * Generated from protobuf field <code>string integratorId = 6;</code>
     */
    protected $integratorId = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $limit
     *           limit is the number of results to return in the response. The backend allows a max value of 100 for this field (which is also what it defaults to).
     *     @type string $startAfter
     *           startAfter indicates where in the record set the search should start. Pass in the last document ID from the previous result to start from here.
     *     @type array<\Eftypay\Common\Query>|\Google\Protobuf\Internal\RepeatedField $queries
     *           queries contains the query conditions applied in the list search.
     *     @type string $orderByField
     *           orderByField set on which fields the resultset is ordered. Defaults to the created date in most cases.
     *     @type int $order
     *           order sets the order direction.
     *     @type string $integratorId
     *           integratorId is an optional field to indicate the integrator data-space. Can only be set by admin.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Common\Common::initOnce();
        parent::__construct($data);
    }

    /**
     * limit is the number of results to return in the response. The backend allows a max value of 100 for this field (which is also what it defaults to).
     *
     * Generated from protobuf field <code>int32 limit = 1;</code>
     * @return int
     */
    public function getLimit()
    {
        return $this->limit;
    }

    /**
     * limit is the number of results to return in the response. The backend allows a max value of 100 for this field (which is also what it defaults to).
     *
     * Generated from protobuf field <code>int32 limit = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setLimit($var)
    {
        GPBUtil::checkInt32($var);
        $this->limit = $var;

        return $this;
    }

    /**
     * startAfter indicates where in the record set the search should start. Pass in the last document ID from the previous result to start from here.
     *
     * Generated from protobuf field <code>string startAfter = 2;</code>
     * @return string
     */
    public function getStartAfter()
    {
        return $this->startAfter;
    }

    /**
     * startAfter indicates where in the record set the search should start. Pass in the last document ID from the previous result to start from here.
     *
     * Generated from protobuf field <code>string startAfter = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setStartAfter($var)
    {
        GPBUtil::checkString($var, True);
        $this->startAfter = $var;

        return $this;
    }

    /**
     * queries contains the query conditions applied in the list search.
     *
     * Generated from protobuf field <code>repeated .eftypay.common.Query queries = 3;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getQueries()
    {
        return $this->queries;
    }

    /**
     * queries contains the query conditions applied in the list search.
     *
     * Generated from protobuf field <code>repeated .eftypay.common.Query queries = 3;</code>
     * @param array<\Eftypay\Common\Query>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setQueries($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Eftypay\Common\Query::class);
        $this->queries = $arr;

        return $this;
    }

    /**
     * orderByField set on which fields the resultset is ordered. Defaults to the created date in most cases.
     *
     * Generated from protobuf field <code>string orderByField = 4;</code>
     * @return string
     */
    public function getOrderByField()
    {
        return $this->orderByField;
    }

    /**
     * orderByField set on which fields the resultset is ordered. Defaults to the created date in most cases.
     *
     * Generated from protobuf field <code>string orderByField = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setOrderByField($var)
    {
        GPBUtil::checkString($var, True);
        $this->orderByField = $var;

        return $this;
    }

    /**
     * order sets the order direction.
     *
     * Generated from protobuf field <code>.eftypay.common.OrderDirection order = 5;</code>
     * @return int
     */
    public function getOrder()
    {
        return $this->order;
    }

    /**
     * order sets the order direction.
     *
     * Generated from protobuf field <code>.eftypay.common.OrderDirection order = 5;</code>
     * @param int $var
     * @return $this
     */
    public function setOrder($var)
    {
        GPBUtil::checkEnum($var, \Eftypay\Common\OrderDirection::class);
        $this->order = $var;

        return $this;
    }

    /**
     * integratorId is an optional field to indicate the integrator data-space. Can only be set by admin.
     *
     * Generated from protobuf field <code>string integratorId = 6;</code>
     * @return string
     */
    public function getIntegratorId()
    {
        return $this->integratorId;
    }

    /**
     * integratorId is an optional field to indicate the integrator data-space. Can only be set by admin.
     *
     * Generated from protobuf field <code>string integratorId = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setIntegratorId($var)
    {
        GPBUtil::checkString($var, True);
        $this->integratorId = $var;

        return $this;
    }

}

