<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common/common.proto

namespace Eftypay\Common;

use UnexpectedValueException;

/**
 * OrderDirection sets in which order the search results are returned.
 *
 * Protobuf type <code>eftypay.common.OrderDirection</code>
 */
class OrderDirection
{
    /**
     * ORDER_DIRECTION_NONE is the default order direction (which is zero and not transmitted on the wire).
     *
     * Generated from protobuf enum <code>ORDER_DIRECTION_NONE = 0;</code>
     */
    const ORDER_DIRECTION_NONE = 0;
    /**
     * ASC ensures the results are returned in ascending order.
     *
     * Generated from protobuf enum <code>ORDER_DIRECTION_ASC = 1;</code>
     */
    const ORDER_DIRECTION_ASC = 1;
    /**
     * DESC ensures the results are returned in descending order.
     *
     * Generated from protobuf enum <code>ORDER_DIRECTION_DESC = 2;</code>
     */
    const ORDER_DIRECTION_DESC = 2;

    private static $valueToName = [
        self::ORDER_DIRECTION_NONE => 'ORDER_DIRECTION_NONE',
        self::ORDER_DIRECTION_ASC => 'ORDER_DIRECTION_ASC',
        self::ORDER_DIRECTION_DESC => 'ORDER_DIRECTION_DESC',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

