<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: public/users/user.proto

namespace Eftypay\Users;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * ApiCredentials contains the API credentials for a user.
 *
 * Generated from protobuf message <code>eftypay.users.ApiCredentials</code>
 */
class ApiCredentials extends \Google\Protobuf\Internal\Message
{
    /**
     * apiKey is the API key for the user.
     *
     * Generated from protobuf field <code>string apiKey = 1;</code>
     */
    protected $apiKey = '';
    /**
     * apiSecret is the API secret for the user.
     *
     * Generated from protobuf field <code>string apiSecret = 2;</code>
     */
    protected $apiSecret = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $apiKey
     *           apiKey is the API key for the user.
     *     @type string $apiSecret
     *           apiSecret is the API secret for the user.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\PBPublic\Users\User::initOnce();
        parent::__construct($data);
    }

    /**
     * apiKey is the API key for the user.
     *
     * Generated from protobuf field <code>string apiKey = 1;</code>
     * @return string
     */
    public function getApiKey()
    {
        return $this->apiKey;
    }

    /**
     * apiKey is the API key for the user.
     *
     * Generated from protobuf field <code>string apiKey = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setApiKey($var)
    {
        GPBUtil::checkString($var, True);
        $this->apiKey = $var;

        return $this;
    }

    /**
     * apiSecret is the API secret for the user.
     *
     * Generated from protobuf field <code>string apiSecret = 2;</code>
     * @return string
     */
    public function getApiSecret()
    {
        return $this->apiSecret;
    }

    /**
     * apiSecret is the API secret for the user.
     *
     * Generated from protobuf field <code>string apiSecret = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setApiSecret($var)
    {
        GPBUtil::checkString($var, True);
        $this->apiSecret = $var;

        return $this;
    }

}

