<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: public/users/user.proto

namespace Eftypay\Users;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * ListUserRequest is used to list the user data. Method only used by administrator
 *
 * Generated from protobuf message <code>eftypay.users.ListUserRequest</code>
 */
class ListUserRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * integratorId is an optional field to indicate the integrator data-space. Can only be set by admin.
     *
     * Generated from protobuf field <code>string integratorId = 1;</code>
     */
    protected $integratorId = '';
    /**
     * listRequest requires all the other query and order data (i.e. where userType=xxx).
     *
     * Generated from protobuf field <code>.eftypay.common.ListRequest listRequest = 2;</code>
     */
    protected $listRequest = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $integratorId
     *           integratorId is an optional field to indicate the integrator data-space. Can only be set by admin.
     *     @type \Eftypay\Common\ListRequest $listRequest
     *           listRequest requires all the other query and order data (i.e. where userType=xxx).
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\PBPublic\Users\User::initOnce();
        parent::__construct($data);
    }

    /**
     * integratorId is an optional field to indicate the integrator data-space. Can only be set by admin.
     *
     * Generated from protobuf field <code>string integratorId = 1;</code>
     * @return string
     */
    public function getIntegratorId()
    {
        return $this->integratorId;
    }

    /**
     * integratorId is an optional field to indicate the integrator data-space. Can only be set by admin.
     *
     * Generated from protobuf field <code>string integratorId = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setIntegratorId($var)
    {
        GPBUtil::checkString($var, True);
        $this->integratorId = $var;

        return $this;
    }

    /**
     * listRequest requires all the other query and order data (i.e. where userType=xxx).
     *
     * Generated from protobuf field <code>.eftypay.common.ListRequest listRequest = 2;</code>
     * @return \Eftypay\Common\ListRequest|null
     */
    public function getListRequest()
    {
        return $this->listRequest;
    }

    public function hasListRequest()
    {
        return isset($this->listRequest);
    }

    public function clearListRequest()
    {
        unset($this->listRequest);
    }

    /**
     * listRequest requires all the other query and order data (i.e. where userType=xxx).
     *
     * Generated from protobuf field <code>.eftypay.common.ListRequest listRequest = 2;</code>
     * @param \Eftypay\Common\ListRequest $var
     * @return $this
     */
    public function setListRequest($var)
    {
        GPBUtil::checkMessage($var, \Eftypay\Common\ListRequest::class);
        $this->listRequest = $var;

        return $this;
    }

}

