<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: public/users/user.proto

namespace Eftypay\Users;

use UnexpectedValueException;

/**
 * UserType signifies the type of user object. A user can be of multiple types.
 *
 * Protobuf type <code>eftypay.users.UserType</code>
 */
class UserType
{
    /**
     * USER_TYPE_NONE is the default user type (which is zero and not transmitted on the wire).
     *
     * Generated from protobuf enum <code>USER_TYPE_NONE = 0;</code>
     */
    const USER_TYPE_NONE = 0;
    /**
     * ADMIN is an (Efty Pay) administrator. This type is mainly used when support is jumping into facilitate a transfer, or contribute to a conversation on a transaction.
     *
     * Generated from protobuf enum <code>ADMIN = 1;</code>
     */
    const ADMIN = 1;
    /**
     * INTEGRATOR is an Efty Pay integrator with API & portal access. It's the main account for an integrator.
     *
     * Generated from protobuf enum <code>INTEGRATOR = 2;</code>
     */
    const INTEGRATOR = 2;
    /**
     * INTEGRATOR_ADMINISTRATOR is an administrators for an integrator with portal access.
     *
     * Generated from protobuf enum <code>INTEGRATOR_ADMINISTRATOR = 3;</code>
     */
    const INTEGRATOR_ADMINISTRATOR = 3;
    /**
     * BUYER_OR_SELLER is a party that is buying or selling digital assets.
     *
     * Generated from protobuf enum <code>BUYER_OR_SELLER = 4;</code>
     */
    const BUYER_OR_SELLER = 4;

    private static $valueToName = [
        self::USER_TYPE_NONE => 'USER_TYPE_NONE',
        self::ADMIN => 'ADMIN',
        self::INTEGRATOR => 'INTEGRATOR',
        self::INTEGRATOR_ADMINISTRATOR => 'INTEGRATOR_ADMINISTRATOR',
        self::BUYER_OR_SELLER => 'BUYER_OR_SELLER',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

