<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: public/messages/messages_service.proto

namespace GPBMetadata\PBPublic\Messages;

class MessagesService
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\PBPublic\Messages\Message::initOnce();
        \GPBMetadata\Google\Api\Annotations::initOnce();
        \GPBMetadata\Includes\ProtocGenOpenapiv2\Openapiv2Annotations::initOnce();
        $pool->internalAddGeneratedFile(
            '
¬
&public/messages/messages_service.protoeftypay.messagesgoogle/api/annotations.proto9includes/protoc-gen-openapiv2/openapiv2-annotations.proto2ú
Messages­
SendMessage$.eftypay.messages.SendMessageRequest.eftypay.messages.Message"]‚Óä“"	/messages:*’AFSend message6Send message adds / sends a message for a transaction.¸
ListMessages%.eftypay.messages.ListMessagesRequest.eftypay.messages.Message"d‚Óä“"/messages/list:*’AHList messages7List messages lists all the messages for a transaction.0‚’A}The Messages service allows for sending / adding messages to transactions. Message methods are only available to integrators.B‘Z<bitbucket.org/eftypay/efty-pay-models/sdk/go/public/messages’APN
Efty Pay - Messages API".
Efty Payhttps://efty.comsupport@efty.com21.0bproto3'
        , true);

        static::$is_initialized = true;
    }
}

