<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: public/transactions/transaction.proto

namespace Eftypay\Transactions;

use UnexpectedValueException;

/**
 * &#64;todo: commissions can be paid by the buyer OR seller.
 *
 * Protobuf type <code>eftypay.transactions.AssetType</code>
 */
class AssetType
{
    /**
     * ASSET_TYPE_NONE is the default asset type (which is zero and not transmitted on the wire).
     *
     * Generated from protobuf enum <code>ASSET_TYPE_NONE = 0;</code>
     */
    const ASSET_TYPE_NONE = 0;
    /**
     * DOMAIN_NAME is a domain name asset type.
     *
     * Generated from protobuf enum <code>DOMAIN_NAME = 1;</code>
     */
    const DOMAIN_NAME = 1;

    private static $valueToName = [
        self::ASSET_TYPE_NONE => 'ASSET_TYPE_NONE',
        self::DOMAIN_NAME => 'DOMAIN_NAME',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

