<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: public/transactions/transaction.proto

namespace Eftypay\Transactions;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * DigitalAsset contains details about the digital asset - only one of the properties of this is set.
 * The reason for not using oneOf is that oneOf is not supported by firestore.
 *
 * Generated from protobuf message <code>eftypay.transactions.DigitalAsset</code>
 */
class DigitalAsset extends \Google\Protobuf\Internal\Message
{
    /**
     * If domain is set then the transaction is for a domain name transfer.
     *
     * Generated from protobuf field <code>.eftypay.domains.Domain domain = 1;</code>
     */
    protected $domain = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Eftypay\Domains\Domain $domain
     *           If domain is set then the transaction is for a domain name transfer.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\PBPublic\Transactions\Transaction::initOnce();
        parent::__construct($data);
    }

    /**
     * If domain is set then the transaction is for a domain name transfer.
     *
     * Generated from protobuf field <code>.eftypay.domains.Domain domain = 1;</code>
     * @return \Eftypay\Domains\Domain|null
     */
    public function getDomain()
    {
        return $this->domain;
    }

    public function hasDomain()
    {
        return isset($this->domain);
    }

    public function clearDomain()
    {
        unset($this->domain);
    }

    /**
     * If domain is set then the transaction is for a domain name transfer.
     *
     * Generated from protobuf field <code>.eftypay.domains.Domain domain = 1;</code>
     * @param \Eftypay\Domains\Domain $var
     * @return $this
     */
    public function setDomain($var)
    {
        GPBUtil::checkMessage($var, \Eftypay\Domains\Domain::class);
        $this->domain = $var;

        return $this;
    }

}

