<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: public/transactions/transaction.proto

namespace Eftypay\Transactions;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * ListTransactionResponse is the object used to input what the query for list transactions looks like.
 *
 * Generated from protobuf message <code>eftypay.transactions.ListTransactionsRequest</code>
 */
class ListTransactionsRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * returnSellerData will return the seller data for all transactions in the response.
     *
     * Generated from protobuf field <code>bool returnSellerData = 1;</code>
     */
    protected $returnSellerData = false;
    /**
     * returnBuyerData will return the buyer data for all transactions in the response.
     *
     * Generated from protobuf field <code>bool returnBuyerData = 2;</code>
     */
    protected $returnBuyerData = false;
    /**
     * listRequest requires all the other query and order data (i.e. where sellerId=xxx).
     *
     * Generated from protobuf field <code>.eftypay.common.ListRequest listRequest = 3;</code>
     */
    protected $listRequest = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type bool $returnSellerData
     *           returnSellerData will return the seller data for all transactions in the response.
     *     @type bool $returnBuyerData
     *           returnBuyerData will return the buyer data for all transactions in the response.
     *     @type \Eftypay\Common\ListRequest $listRequest
     *           listRequest requires all the other query and order data (i.e. where sellerId=xxx).
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\PBPublic\Transactions\Transaction::initOnce();
        parent::__construct($data);
    }

    /**
     * returnSellerData will return the seller data for all transactions in the response.
     *
     * Generated from protobuf field <code>bool returnSellerData = 1;</code>
     * @return bool
     */
    public function getReturnSellerData()
    {
        return $this->returnSellerData;
    }

    /**
     * returnSellerData will return the seller data for all transactions in the response.
     *
     * Generated from protobuf field <code>bool returnSellerData = 1;</code>
     * @param bool $var
     * @return $this
     */
    public function setReturnSellerData($var)
    {
        GPBUtil::checkBool($var);
        $this->returnSellerData = $var;

        return $this;
    }

    /**
     * returnBuyerData will return the buyer data for all transactions in the response.
     *
     * Generated from protobuf field <code>bool returnBuyerData = 2;</code>
     * @return bool
     */
    public function getReturnBuyerData()
    {
        return $this->returnBuyerData;
    }

    /**
     * returnBuyerData will return the buyer data for all transactions in the response.
     *
     * Generated from protobuf field <code>bool returnBuyerData = 2;</code>
     * @param bool $var
     * @return $this
     */
    public function setReturnBuyerData($var)
    {
        GPBUtil::checkBool($var);
        $this->returnBuyerData = $var;

        return $this;
    }

    /**
     * listRequest requires all the other query and order data (i.e. where sellerId=xxx).
     *
     * Generated from protobuf field <code>.eftypay.common.ListRequest listRequest = 3;</code>
     * @return \Eftypay\Common\ListRequest|null
     */
    public function getListRequest()
    {
        return $this->listRequest;
    }

    public function hasListRequest()
    {
        return isset($this->listRequest);
    }

    public function clearListRequest()
    {
        unset($this->listRequest);
    }

    /**
     * listRequest requires all the other query and order data (i.e. where sellerId=xxx).
     *
     * Generated from protobuf field <code>.eftypay.common.ListRequest listRequest = 3;</code>
     * @param \Eftypay\Common\ListRequest $var
     * @return $this
     */
    public function setListRequest($var)
    {
        GPBUtil::checkMessage($var, \Eftypay\Common\ListRequest::class);
        $this->listRequest = $var;

        return $this;
    }

}

