<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: public/transactions/transaction.proto

namespace Eftypay\Transactions;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * TransactionRequest is used in the create, update & delete transaction calls.
 *
 * Generated from protobuf message <code>eftypay.transactions.TransactionRequest</code>
 */
class TransactionRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * integratorId is an optional field to indicate the integrator data-space. Can only be set by admin.
     *
     * Generated from protobuf field <code>string integratorId = 1;</code>
     */
    protected $integratorId = '';
    /**
     * transaction contains the transaction details.
     *
     * Generated from protobuf field <code>.eftypay.transactions.Transaction transaction = 2;</code>
     */
    protected $transaction = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $integratorId
     *           integratorId is an optional field to indicate the integrator data-space. Can only be set by admin.
     *     @type \Eftypay\Transactions\Transaction $transaction
     *           transaction contains the transaction details.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\PBPublic\Transactions\Transaction::initOnce();
        parent::__construct($data);
    }

    /**
     * integratorId is an optional field to indicate the integrator data-space. Can only be set by admin.
     *
     * Generated from protobuf field <code>string integratorId = 1;</code>
     * @return string
     */
    public function getIntegratorId()
    {
        return $this->integratorId;
    }

    /**
     * integratorId is an optional field to indicate the integrator data-space. Can only be set by admin.
     *
     * Generated from protobuf field <code>string integratorId = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setIntegratorId($var)
    {
        GPBUtil::checkString($var, True);
        $this->integratorId = $var;

        return $this;
    }

    /**
     * transaction contains the transaction details.
     *
     * Generated from protobuf field <code>.eftypay.transactions.Transaction transaction = 2;</code>
     * @return \Eftypay\Transactions\Transaction|null
     */
    public function getTransaction()
    {
        return $this->transaction;
    }

    public function hasTransaction()
    {
        return isset($this->transaction);
    }

    public function clearTransaction()
    {
        unset($this->transaction);
    }

    /**
     * transaction contains the transaction details.
     *
     * Generated from protobuf field <code>.eftypay.transactions.Transaction transaction = 2;</code>
     * @param \Eftypay\Transactions\Transaction $var
     * @return $this
     */
    public function setTransaction($var)
    {
        GPBUtil::checkMessage($var, \Eftypay\Transactions\Transaction::class);
        $this->transaction = $var;

        return $this;
    }

}

