<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: public/transactions/transaction.proto

namespace Eftypay\Transactions;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * TransactionMagicLinkPayload is used internally. The object is used encrypted in communications to the buyer / seller re. OTP logins for transaction details.
 * One a user clicks the magic link, an OTP email is sent to the registered email address. OTP's are valid for 15 minutes from generation.
 * Once a user uses an OTP to login, the OTP is 'exchanged' for a JWT, the OTP is then deleted.
 * JWT's generated by an OTP are valid for 15 minutes.
 *
 * Generated from protobuf message <code>eftypay.transactions.TransactionMagicLinkPayload</code>
 */
class TransactionMagicLinkPayload extends \Google\Protobuf\Internal\Message
{
    /**
     * transactionId is the ID of the transaction to send the magic email for.
     *
     * Generated from protobuf field <code>string transactionId = 1;</code>
     */
    protected $transactionId = '';
    /**
     * sendToBuyer, if set to true, sends the magic link email to the buyer of the transaction.
     *
     * Generated from protobuf field <code>bool sendToBuyer = 2;</code>
     */
    protected $sendToBuyer = false;
    /**
     * sendToSeller, if set to true, sends the magic link email to the seller in the transaction.
     *
     * Generated from protobuf field <code>bool sendToSeller = 3;</code>
     */
    protected $sendToSeller = false;
    /**
     * integratorId is an optional field to indicate the integrator data-space. Can only be set by admin.
     *
     * Generated from protobuf field <code>string integratorId = 4;</code>
     */
    protected $integratorId = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $transactionId
     *           transactionId is the ID of the transaction to send the magic email for.
     *     @type bool $sendToBuyer
     *           sendToBuyer, if set to true, sends the magic link email to the buyer of the transaction.
     *     @type bool $sendToSeller
     *           sendToSeller, if set to true, sends the magic link email to the seller in the transaction.
     *     @type string $integratorId
     *           integratorId is an optional field to indicate the integrator data-space. Can only be set by admin.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\PBPublic\Transactions\Transaction::initOnce();
        parent::__construct($data);
    }

    /**
     * transactionId is the ID of the transaction to send the magic email for.
     *
     * Generated from protobuf field <code>string transactionId = 1;</code>
     * @return string
     */
    public function getTransactionId()
    {
        return $this->transactionId;
    }

    /**
     * transactionId is the ID of the transaction to send the magic email for.
     *
     * Generated from protobuf field <code>string transactionId = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setTransactionId($var)
    {
        GPBUtil::checkString($var, True);
        $this->transactionId = $var;

        return $this;
    }

    /**
     * sendToBuyer, if set to true, sends the magic link email to the buyer of the transaction.
     *
     * Generated from protobuf field <code>bool sendToBuyer = 2;</code>
     * @return bool
     */
    public function getSendToBuyer()
    {
        return $this->sendToBuyer;
    }

    /**
     * sendToBuyer, if set to true, sends the magic link email to the buyer of the transaction.
     *
     * Generated from protobuf field <code>bool sendToBuyer = 2;</code>
     * @param bool $var
     * @return $this
     */
    public function setSendToBuyer($var)
    {
        GPBUtil::checkBool($var);
        $this->sendToBuyer = $var;

        return $this;
    }

    /**
     * sendToSeller, if set to true, sends the magic link email to the seller in the transaction.
     *
     * Generated from protobuf field <code>bool sendToSeller = 3;</code>
     * @return bool
     */
    public function getSendToSeller()
    {
        return $this->sendToSeller;
    }

    /**
     * sendToSeller, if set to true, sends the magic link email to the seller in the transaction.
     *
     * Generated from protobuf field <code>bool sendToSeller = 3;</code>
     * @param bool $var
     * @return $this
     */
    public function setSendToSeller($var)
    {
        GPBUtil::checkBool($var);
        $this->sendToSeller = $var;

        return $this;
    }

    /**
     * integratorId is an optional field to indicate the integrator data-space. Can only be set by admin.
     *
     * Generated from protobuf field <code>string integratorId = 4;</code>
     * @return string
     */
    public function getIntegratorId()
    {
        return $this->integratorId;
    }

    /**
     * integratorId is an optional field to indicate the integrator data-space. Can only be set by admin.
     *
     * Generated from protobuf field <code>string integratorId = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setIntegratorId($var)
    {
        GPBUtil::checkString($var, True);
        $this->integratorId = $var;

        return $this;
    }

}

