<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: public/transactions/transaction.proto

namespace Eftypay\Transactions;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * UtmParameters contains UTM tracking parameters for the transaction.
 *
 * Generated from protobuf message <code>eftypay.transactions.UtmParameters</code>
 */
class UtmParameters extends \Google\Protobuf\Internal\Message
{
    /**
     * utmSource is the source of transaction, for example efty.com.
     *
     * Generated from protobuf field <code>string utmSource = 1;</code>
     */
    protected $utmSource = '';
    /**
     * utmMedium is the type of medium, i.e. email, CPC, etc.
     *
     * Generated from protobuf field <code>string utmMedium = 2;</code>
     */
    protected $utmMedium = '';
    /**
     * utmCampaign is the campaign that the transaction was created out of.
     *
     * Generated from protobuf field <code>string utmCampaign = 3;</code>
     */
    protected $utmCampaign = '';
    /**
     * utmTerm contains relevant keywords.
     *
     * Generated from protobuf field <code>string utmTerm = 4;</code>
     */
    protected $utmTerm = '';
    /**
     * utmContent contains the ID of the specific button, link, that caused the transaction to be created.
     *
     * Generated from protobuf field <code>string utmContent = 5;</code>
     */
    protected $utmContent = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $utmSource
     *           utmSource is the source of transaction, for example efty.com.
     *     @type string $utmMedium
     *           utmMedium is the type of medium, i.e. email, CPC, etc.
     *     @type string $utmCampaign
     *           utmCampaign is the campaign that the transaction was created out of.
     *     @type string $utmTerm
     *           utmTerm contains relevant keywords.
     *     @type string $utmContent
     *           utmContent contains the ID of the specific button, link, that caused the transaction to be created.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\PBPublic\Transactions\Transaction::initOnce();
        parent::__construct($data);
    }

    /**
     * utmSource is the source of transaction, for example efty.com.
     *
     * Generated from protobuf field <code>string utmSource = 1;</code>
     * @return string
     */
    public function getUtmSource()
    {
        return $this->utmSource;
    }

    /**
     * utmSource is the source of transaction, for example efty.com.
     *
     * Generated from protobuf field <code>string utmSource = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setUtmSource($var)
    {
        GPBUtil::checkString($var, True);
        $this->utmSource = $var;

        return $this;
    }

    /**
     * utmMedium is the type of medium, i.e. email, CPC, etc.
     *
     * Generated from protobuf field <code>string utmMedium = 2;</code>
     * @return string
     */
    public function getUtmMedium()
    {
        return $this->utmMedium;
    }

    /**
     * utmMedium is the type of medium, i.e. email, CPC, etc.
     *
     * Generated from protobuf field <code>string utmMedium = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setUtmMedium($var)
    {
        GPBUtil::checkString($var, True);
        $this->utmMedium = $var;

        return $this;
    }

    /**
     * utmCampaign is the campaign that the transaction was created out of.
     *
     * Generated from protobuf field <code>string utmCampaign = 3;</code>
     * @return string
     */
    public function getUtmCampaign()
    {
        return $this->utmCampaign;
    }

    /**
     * utmCampaign is the campaign that the transaction was created out of.
     *
     * Generated from protobuf field <code>string utmCampaign = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setUtmCampaign($var)
    {
        GPBUtil::checkString($var, True);
        $this->utmCampaign = $var;

        return $this;
    }

    /**
     * utmTerm contains relevant keywords.
     *
     * Generated from protobuf field <code>string utmTerm = 4;</code>
     * @return string
     */
    public function getUtmTerm()
    {
        return $this->utmTerm;
    }

    /**
     * utmTerm contains relevant keywords.
     *
     * Generated from protobuf field <code>string utmTerm = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setUtmTerm($var)
    {
        GPBUtil::checkString($var, True);
        $this->utmTerm = $var;

        return $this;
    }

    /**
     * utmContent contains the ID of the specific button, link, that caused the transaction to be created.
     *
     * Generated from protobuf field <code>string utmContent = 5;</code>
     * @return string
     */
    public function getUtmContent()
    {
        return $this->utmContent;
    }

    /**
     * utmContent contains the ID of the specific button, link, that caused the transaction to be created.
     *
     * Generated from protobuf field <code>string utmContent = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setUtmContent($var)
    {
        GPBUtil::checkString($var, True);
        $this->utmContent = $var;

        return $this;
    }

}

