<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: public/finances/vat.proto

namespace GPBMetadata\PBPublic\Finances;

class Vat
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Common\Finance::initOnce();
        $pool->internalAddGeneratedFile(
            '
­
public/finances/vat.protoeftypay.finances"ú
CalculateVatRequest
itemPriceWithoutVat (
supplierChargesVat (4
supplierCountry (2.eftypay.common.CountryCode!
supplierRepresentsCompany (1
buyerCountry (2.eftypay.common.CountryCode
buyerRepresentsCompany ("¸
CalculateVatResponse
	chargeVat (
vatOutOfScope (
vatReverseCharge (
vatOneStopShop (
vatPercentage (
	vatAmount (
amountIncludingVat (B>Z<bitbucket.org/eftypay/efty-pay-models/sdk/go/public/financesbproto3'
        , true);

        static::$is_initialized = true;
    }
}

