<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: public/payments/mangopay/onboarding.proto

namespace Eftypay\Payments\Mangopay;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Address contains address details as required by Mangopay.
 *
 * Generated from protobuf message <code>eftypay.payments.mangopay.Address</code>
 */
class Address extends \Google\Protobuf\Internal\Message
{
    /**
     * addressLine1 contains the first line of the address.
     *
     * Generated from protobuf field <code>string addressLine1 = 1;</code>
     */
    protected $addressLine1 = '';
    /**
     * addressLine2 contains the second line of the address.
     *
     * Generated from protobuf field <code>string addressLine2 = 2;</code>
     */
    protected $addressLine2 = '';
    /**
     * city contains the city of the address.
     *
     * Generated from protobuf field <code>string city = 3;</code>
     */
    protected $city = '';
    /**
     * regionOrCounty contains the region / country of the address. This field is optional except if the Country is US, CA, or MX.
     *
     * Generated from protobuf field <code>string regionOrCounty = 4;</code>
     */
    protected $regionOrCounty = '';
    /**
     * postalCode contains the postal code of the address. The postal code can contain the following characters: alphanumeric, dashes, and spaces.
     *
     * Generated from protobuf field <code>string postalCode = 5;</code>
     */
    protected $postalCode = '';
    /**
     * country contains the country of the address in the ISO 3166-1 alpha-2 format: https://mangopay.com/docs/api-basics/data-formats
     *
     * Generated from protobuf field <code>.eftypay.common.CountryCode country = 6;</code>
     */
    protected $country = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $addressLine1
     *           addressLine1 contains the first line of the address.
     *     @type string $addressLine2
     *           addressLine2 contains the second line of the address.
     *     @type string $city
     *           city contains the city of the address.
     *     @type string $regionOrCounty
     *           regionOrCounty contains the region / country of the address. This field is optional except if the Country is US, CA, or MX.
     *     @type string $postalCode
     *           postalCode contains the postal code of the address. The postal code can contain the following characters: alphanumeric, dashes, and spaces.
     *     @type int $country
     *           country contains the country of the address in the ISO 3166-1 alpha-2 format: https://mangopay.com/docs/api-basics/data-formats
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\PBPublic\Payments\Mangopay\Onboarding::initOnce();
        parent::__construct($data);
    }

    /**
     * addressLine1 contains the first line of the address.
     *
     * Generated from protobuf field <code>string addressLine1 = 1;</code>
     * @return string
     */
    public function getAddressLine1()
    {
        return $this->addressLine1;
    }

    /**
     * addressLine1 contains the first line of the address.
     *
     * Generated from protobuf field <code>string addressLine1 = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setAddressLine1($var)
    {
        GPBUtil::checkString($var, True);
        $this->addressLine1 = $var;

        return $this;
    }

    /**
     * addressLine2 contains the second line of the address.
     *
     * Generated from protobuf field <code>string addressLine2 = 2;</code>
     * @return string
     */
    public function getAddressLine2()
    {
        return $this->addressLine2;
    }

    /**
     * addressLine2 contains the second line of the address.
     *
     * Generated from protobuf field <code>string addressLine2 = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setAddressLine2($var)
    {
        GPBUtil::checkString($var, True);
        $this->addressLine2 = $var;

        return $this;
    }

    /**
     * city contains the city of the address.
     *
     * Generated from protobuf field <code>string city = 3;</code>
     * @return string
     */
    public function getCity()
    {
        return $this->city;
    }

    /**
     * city contains the city of the address.
     *
     * Generated from protobuf field <code>string city = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setCity($var)
    {
        GPBUtil::checkString($var, True);
        $this->city = $var;

        return $this;
    }

    /**
     * regionOrCounty contains the region / country of the address. This field is optional except if the Country is US, CA, or MX.
     *
     * Generated from protobuf field <code>string regionOrCounty = 4;</code>
     * @return string
     */
    public function getRegionOrCounty()
    {
        return $this->regionOrCounty;
    }

    /**
     * regionOrCounty contains the region / country of the address. This field is optional except if the Country is US, CA, or MX.
     *
     * Generated from protobuf field <code>string regionOrCounty = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setRegionOrCounty($var)
    {
        GPBUtil::checkString($var, True);
        $this->regionOrCounty = $var;

        return $this;
    }

    /**
     * postalCode contains the postal code of the address. The postal code can contain the following characters: alphanumeric, dashes, and spaces.
     *
     * Generated from protobuf field <code>string postalCode = 5;</code>
     * @return string
     */
    public function getPostalCode()
    {
        return $this->postalCode;
    }

    /**
     * postalCode contains the postal code of the address. The postal code can contain the following characters: alphanumeric, dashes, and spaces.
     *
     * Generated from protobuf field <code>string postalCode = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setPostalCode($var)
    {
        GPBUtil::checkString($var, True);
        $this->postalCode = $var;

        return $this;
    }

    /**
     * country contains the country of the address in the ISO 3166-1 alpha-2 format: https://mangopay.com/docs/api-basics/data-formats
     *
     * Generated from protobuf field <code>.eftypay.common.CountryCode country = 6;</code>
     * @return int
     */
    public function getCountry()
    {
        return $this->country;
    }

    /**
     * country contains the country of the address in the ISO 3166-1 alpha-2 format: https://mangopay.com/docs/api-basics/data-formats
     *
     * Generated from protobuf field <code>.eftypay.common.CountryCode country = 6;</code>
     * @param int $var
     * @return $this
     */
    public function setCountry($var)
    {
        GPBUtil::checkEnum($var, \Eftypay\Common\CountryCode::class);
        $this->country = $var;

        return $this;
    }

}

