<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: public/payments/mangopay/onboarding.proto

namespace Eftypay\Payments\Mangopay;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>eftypay.payments.mangopay.BirthPlace</code>
 */
class BirthPlace extends \Google\Protobuf\Internal\Message
{
    /**
     * city contains the city of the address.
     *
     * Generated from protobuf field <code>string city = 1;</code>
     */
    protected $city = '';
    /**
     * country contains the country of the address in the ISO 3166-1 alpha-2 format: https://mangopay.com/docs/api-basics/data-formats
     *
     * Generated from protobuf field <code>.eftypay.common.CountryCode country = 2;</code>
     */
    protected $country = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $city
     *           city contains the city of the address.
     *     @type int $country
     *           country contains the country of the address in the ISO 3166-1 alpha-2 format: https://mangopay.com/docs/api-basics/data-formats
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\PBPublic\Payments\Mangopay\Onboarding::initOnce();
        parent::__construct($data);
    }

    /**
     * city contains the city of the address.
     *
     * Generated from protobuf field <code>string city = 1;</code>
     * @return string
     */
    public function getCity()
    {
        return $this->city;
    }

    /**
     * city contains the city of the address.
     *
     * Generated from protobuf field <code>string city = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setCity($var)
    {
        GPBUtil::checkString($var, True);
        $this->city = $var;

        return $this;
    }

    /**
     * country contains the country of the address in the ISO 3166-1 alpha-2 format: https://mangopay.com/docs/api-basics/data-formats
     *
     * Generated from protobuf field <code>.eftypay.common.CountryCode country = 2;</code>
     * @return int
     */
    public function getCountry()
    {
        return $this->country;
    }

    /**
     * country contains the country of the address in the ISO 3166-1 alpha-2 format: https://mangopay.com/docs/api-basics/data-formats
     *
     * Generated from protobuf field <code>.eftypay.common.CountryCode country = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setCountry($var)
    {
        GPBUtil::checkEnum($var, \Eftypay\Common\CountryCode::class);
        $this->country = $var;

        return $this;
    }

}

