<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: public/payments/mangopay/mangopay.proto

namespace Eftypay\Payments\Mangopay;

use UnexpectedValueException;

/**
 * KycLevel contains the KYC Level from Mangopay.
 *
 * Protobuf type <code>eftypay.payments.mangopay.KycLevel</code>
 */
class KycLevel
{
    /**
     * KYC_LEVEL_NONE is the default KYC status (which is zero and not transmitted on the wire).
     *
     * Generated from protobuf enum <code>KYC_LEVEL_NONE = 0;</code>
     */
    const KYC_LEVEL_NONE = 0;
    /**
     * LIGHT means the user is not yet verified by Mangopay, assigned by default to all users.
     *
     * Generated from protobuf enum <code>LIGHT = 1;</code>
     */
    const LIGHT = 1;
    /**
     * VERIFIED means the user has successfully completed the verification process and had the necessary documents validated by Mangopay. Only users whose UserCategory is OWNER can submit verification documents for validation. Only users whose KYCLevel is REGULAR can request payouts.
     *
     * Generated from protobuf enum <code>REGULAR = 2;</code>
     */
    const REGULAR = 2;

    private static $valueToName = [
        self::KYC_LEVEL_NONE => 'KYC_LEVEL_NONE',
        self::LIGHT => 'LIGHT',
        self::REGULAR => 'REGULAR',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

