<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: public/payments/mangopay/onboarding.proto

namespace Eftypay\Payments\Mangopay;

use UnexpectedValueException;

/**
 * LegalUserType contains the different legal types supported by Mangopay.
 *
 * Protobuf type <code>eftypay.payments.mangopay.LegalUserType</code>
 */
class LegalUserType
{
    /**
     * LEGAL_USER_TYPE_NONE is the default legal type (which is zero and not transmitted on the wire).
     *
     * Generated from protobuf enum <code>LEGAL_USER_TYPE_NONE = 0;</code>
     */
    const LEGAL_USER_TYPE_NONE = 0;
    /**
     * BUSINESS is the legal user type to use for a business.
     *
     * Generated from protobuf enum <code>BUSINESS = 1;</code>
     */
    const BUSINESS = 1;
    /**
     * PARTNERSHIP is the legal user type to use for a partnership.
     *
     * Generated from protobuf enum <code>PARTNERSHIP = 2;</code>
     */
    const PARTNERSHIP = 2;
    /**
     * ORGANIZATION is the legal type to use for an organization.
     *
     * Generated from protobuf enum <code>ORGANIZATION = 3;</code>
     */
    const ORGANIZATION = 3;
    /**
     * LEGAL_USER_TYPE_SOLETRADER  is the legal type to use for a sole trader.
     *
     * Generated from protobuf enum <code>SOLETRADER = 4;</code>
     */
    const SOLETRADER = 4;

    private static $valueToName = [
        self::LEGAL_USER_TYPE_NONE => 'LEGAL_USER_TYPE_NONE',
        self::BUSINESS => 'BUSINESS',
        self::PARTNERSHIP => 'PARTNERSHIP',
        self::ORGANIZATION => 'ORGANIZATION',
        self::SOLETRADER => 'SOLETRADER',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

