<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: public/payments/mangopay/onboarding.proto

namespace Eftypay\Payments\Mangopay;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * LegalUser requires information about the legal user.
 *
 * Generated from protobuf message <code>eftypay.payments.mangopay.LegalUser</code>
 */
class LegalUser extends \Google\Protobuf\Internal\Message
{
    /**
     * registeredName contains the registered name of the entity. This needs to match the name on all required documents provided.
     *
     * Generated from protobuf field <code>string registeredName = 1;</code>
     */
    protected $registeredName = '';
    /**
     * companyNumber contains the company registration number. Only required when legalUserType is BUSINESS or PARTNERSHIP.
     *
     * Generated from protobuf field <code>string companyNumber = 2;</code>
     */
    protected $companyNumber = '';
    /**
     * email contains the email address for the legal entity.
     *
     * Generated from protobuf field <code>string email = 3;</code>
     */
    protected $email = '';
    /**
     * registeredAddress contains the registered address of the entity’s headquarters.
     *
     * Generated from protobuf field <code>.eftypay.payments.mangopay.Address registeredAddress = 4;</code>
     */
    protected $registeredAddress = null;
    /**
     * legalRepresentative contains the details of the legal representative of the entity or the sole proprietor.
     *
     * Generated from protobuf field <code>.eftypay.payments.mangopay.Person legalRepresentative = 5;</code>
     */
    protected $legalRepresentative = null;
    /**
     * uboDeclaration contains information of all owners of the business that own 25% or more of the shares. Only required when legalUserType is BUSINESS or PARTNERSHIP. The object contains additional nested information in case an UBO declaration is refused.
     *
     * Generated from protobuf field <code>.eftypay.payments.mangopay.UboDeclaration uboDeclaration = 6;</code>
     */
    protected $uboDeclaration = null;
    /**
     * LegalUserType contains the type of legal user. This field cannot change on UPDATE.
     *
     * Generated from protobuf field <code>.eftypay.payments.mangopay.LegalUserType legalUserType = 7;</code>
     */
    protected $legalUserType = 0;
    /**
     * vatNumber is an optional field that contains the VAT number for the legal user.
     *
     * Generated from protobuf field <code>string vatNumber = 8;</code>
     */
    protected $vatNumber = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $registeredName
     *           registeredName contains the registered name of the entity. This needs to match the name on all required documents provided.
     *     @type string $companyNumber
     *           companyNumber contains the company registration number. Only required when legalUserType is BUSINESS or PARTNERSHIP.
     *     @type string $email
     *           email contains the email address for the legal entity.
     *     @type \Eftypay\Payments\Mangopay\Address $registeredAddress
     *           registeredAddress contains the registered address of the entity’s headquarters.
     *     @type \Eftypay\Payments\Mangopay\Person $legalRepresentative
     *           legalRepresentative contains the details of the legal representative of the entity or the sole proprietor.
     *     @type \Eftypay\Payments\Mangopay\UboDeclaration $uboDeclaration
     *           uboDeclaration contains information of all owners of the business that own 25% or more of the shares. Only required when legalUserType is BUSINESS or PARTNERSHIP. The object contains additional nested information in case an UBO declaration is refused.
     *     @type int $legalUserType
     *           LegalUserType contains the type of legal user. This field cannot change on UPDATE.
     *     @type string $vatNumber
     *           vatNumber is an optional field that contains the VAT number for the legal user.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\PBPublic\Payments\Mangopay\Onboarding::initOnce();
        parent::__construct($data);
    }

    /**
     * registeredName contains the registered name of the entity. This needs to match the name on all required documents provided.
     *
     * Generated from protobuf field <code>string registeredName = 1;</code>
     * @return string
     */
    public function getRegisteredName()
    {
        return $this->registeredName;
    }

    /**
     * registeredName contains the registered name of the entity. This needs to match the name on all required documents provided.
     *
     * Generated from protobuf field <code>string registeredName = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setRegisteredName($var)
    {
        GPBUtil::checkString($var, True);
        $this->registeredName = $var;

        return $this;
    }

    /**
     * companyNumber contains the company registration number. Only required when legalUserType is BUSINESS or PARTNERSHIP.
     *
     * Generated from protobuf field <code>string companyNumber = 2;</code>
     * @return string
     */
    public function getCompanyNumber()
    {
        return $this->companyNumber;
    }

    /**
     * companyNumber contains the company registration number. Only required when legalUserType is BUSINESS or PARTNERSHIP.
     *
     * Generated from protobuf field <code>string companyNumber = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setCompanyNumber($var)
    {
        GPBUtil::checkString($var, True);
        $this->companyNumber = $var;

        return $this;
    }

    /**
     * email contains the email address for the legal entity.
     *
     * Generated from protobuf field <code>string email = 3;</code>
     * @return string
     */
    public function getEmail()
    {
        return $this->email;
    }

    /**
     * email contains the email address for the legal entity.
     *
     * Generated from protobuf field <code>string email = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setEmail($var)
    {
        GPBUtil::checkString($var, True);
        $this->email = $var;

        return $this;
    }

    /**
     * registeredAddress contains the registered address of the entity’s headquarters.
     *
     * Generated from protobuf field <code>.eftypay.payments.mangopay.Address registeredAddress = 4;</code>
     * @return \Eftypay\Payments\Mangopay\Address|null
     */
    public function getRegisteredAddress()
    {
        return $this->registeredAddress;
    }

    public function hasRegisteredAddress()
    {
        return isset($this->registeredAddress);
    }

    public function clearRegisteredAddress()
    {
        unset($this->registeredAddress);
    }

    /**
     * registeredAddress contains the registered address of the entity’s headquarters.
     *
     * Generated from protobuf field <code>.eftypay.payments.mangopay.Address registeredAddress = 4;</code>
     * @param \Eftypay\Payments\Mangopay\Address $var
     * @return $this
     */
    public function setRegisteredAddress($var)
    {
        GPBUtil::checkMessage($var, \Eftypay\Payments\Mangopay\Address::class);
        $this->registeredAddress = $var;

        return $this;
    }

    /**
     * legalRepresentative contains the details of the legal representative of the entity or the sole proprietor.
     *
     * Generated from protobuf field <code>.eftypay.payments.mangopay.Person legalRepresentative = 5;</code>
     * @return \Eftypay\Payments\Mangopay\Person|null
     */
    public function getLegalRepresentative()
    {
        return $this->legalRepresentative;
    }

    public function hasLegalRepresentative()
    {
        return isset($this->legalRepresentative);
    }

    public function clearLegalRepresentative()
    {
        unset($this->legalRepresentative);
    }

    /**
     * legalRepresentative contains the details of the legal representative of the entity or the sole proprietor.
     *
     * Generated from protobuf field <code>.eftypay.payments.mangopay.Person legalRepresentative = 5;</code>
     * @param \Eftypay\Payments\Mangopay\Person $var
     * @return $this
     */
    public function setLegalRepresentative($var)
    {
        GPBUtil::checkMessage($var, \Eftypay\Payments\Mangopay\Person::class);
        $this->legalRepresentative = $var;

        return $this;
    }

    /**
     * uboDeclaration contains information of all owners of the business that own 25% or more of the shares. Only required when legalUserType is BUSINESS or PARTNERSHIP. The object contains additional nested information in case an UBO declaration is refused.
     *
     * Generated from protobuf field <code>.eftypay.payments.mangopay.UboDeclaration uboDeclaration = 6;</code>
     * @return \Eftypay\Payments\Mangopay\UboDeclaration|null
     */
    public function getUboDeclaration()
    {
        return $this->uboDeclaration;
    }

    public function hasUboDeclaration()
    {
        return isset($this->uboDeclaration);
    }

    public function clearUboDeclaration()
    {
        unset($this->uboDeclaration);
    }

    /**
     * uboDeclaration contains information of all owners of the business that own 25% or more of the shares. Only required when legalUserType is BUSINESS or PARTNERSHIP. The object contains additional nested information in case an UBO declaration is refused.
     *
     * Generated from protobuf field <code>.eftypay.payments.mangopay.UboDeclaration uboDeclaration = 6;</code>
     * @param \Eftypay\Payments\Mangopay\UboDeclaration $var
     * @return $this
     */
    public function setUboDeclaration($var)
    {
        GPBUtil::checkMessage($var, \Eftypay\Payments\Mangopay\UboDeclaration::class);
        $this->uboDeclaration = $var;

        return $this;
    }

    /**
     * LegalUserType contains the type of legal user. This field cannot change on UPDATE.
     *
     * Generated from protobuf field <code>.eftypay.payments.mangopay.LegalUserType legalUserType = 7;</code>
     * @return int
     */
    public function getLegalUserType()
    {
        return $this->legalUserType;
    }

    /**
     * LegalUserType contains the type of legal user. This field cannot change on UPDATE.
     *
     * Generated from protobuf field <code>.eftypay.payments.mangopay.LegalUserType legalUserType = 7;</code>
     * @param int $var
     * @return $this
     */
    public function setLegalUserType($var)
    {
        GPBUtil::checkEnum($var, \Eftypay\Payments\Mangopay\LegalUserType::class);
        $this->legalUserType = $var;

        return $this;
    }

    /**
     * vatNumber is an optional field that contains the VAT number for the legal user.
     *
     * Generated from protobuf field <code>string vatNumber = 8;</code>
     * @return string
     */
    public function getVatNumber()
    {
        return $this->vatNumber;
    }

    /**
     * vatNumber is an optional field that contains the VAT number for the legal user.
     *
     * Generated from protobuf field <code>string vatNumber = 8;</code>
     * @param string $var
     * @return $this
     */
    public function setVatNumber($var)
    {
        GPBUtil::checkString($var, True);
        $this->vatNumber = $var;

        return $this;
    }

}

