<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: public/payments/mangopay/checkout.proto

namespace Eftypay\Payments\Mangopay;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * MangopayDetails contains the payment details for Mangopay.
 *
 * Generated from protobuf message <code>eftypay.payments.mangopay.MangopayDetails</code>
 */
class MangopayDetails extends \Google\Protobuf\Internal\Message
{
    /**
     * onboardAsSellerWithMangopay if set to true will kick of the onboarding process with Mangopay.
     *
     * Generated from protobuf field <code>bool onboardAsSellerWithMangopay = 1;</code>
     */
    protected $onboardAsSellerWithMangopay = false;
    /**
     * userCategory should be set to OWNER in case the user is (also) a seller. In case of a buyer this should be set to PAYER.
     *
     * Generated from protobuf field <code>.eftypay.payments.mangopay.UserCategory userCategory = 2;</code>
     */
    protected $userCategory = 0;
    /**
     * userId is the Mangopay userId. This is a read only field, set by Efty Pay and only used internally.
     *
     * Generated from protobuf field <code>string userId = 3;</code>
     */
    protected $userId = '';
    /**
     * kycLevel contains the KYC level from Mangopay, only set for users of type OWNER. Readonly field set by Efty Pay.
     *
     * Generated from protobuf field <code>.eftypay.payments.mangopay.KycLevel kycLevel = 4;</code>
     */
    protected $kycLevel = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type bool $onboardAsSellerWithMangopay
     *           onboardAsSellerWithMangopay if set to true will kick of the onboarding process with Mangopay.
     *     @type int $userCategory
     *           userCategory should be set to OWNER in case the user is (also) a seller. In case of a buyer this should be set to PAYER.
     *     @type string $userId
     *           userId is the Mangopay userId. This is a read only field, set by Efty Pay and only used internally.
     *     @type int $kycLevel
     *           kycLevel contains the KYC level from Mangopay, only set for users of type OWNER. Readonly field set by Efty Pay.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\PBPublic\Payments\Mangopay\Checkout::initOnce();
        parent::__construct($data);
    }

    /**
     * onboardAsSellerWithMangopay if set to true will kick of the onboarding process with Mangopay.
     *
     * Generated from protobuf field <code>bool onboardAsSellerWithMangopay = 1;</code>
     * @return bool
     */
    public function getOnboardAsSellerWithMangopay()
    {
        return $this->onboardAsSellerWithMangopay;
    }

    /**
     * onboardAsSellerWithMangopay if set to true will kick of the onboarding process with Mangopay.
     *
     * Generated from protobuf field <code>bool onboardAsSellerWithMangopay = 1;</code>
     * @param bool $var
     * @return $this
     */
    public function setOnboardAsSellerWithMangopay($var)
    {
        GPBUtil::checkBool($var);
        $this->onboardAsSellerWithMangopay = $var;

        return $this;
    }

    /**
     * userCategory should be set to OWNER in case the user is (also) a seller. In case of a buyer this should be set to PAYER.
     *
     * Generated from protobuf field <code>.eftypay.payments.mangopay.UserCategory userCategory = 2;</code>
     * @return int
     */
    public function getUserCategory()
    {
        return $this->userCategory;
    }

    /**
     * userCategory should be set to OWNER in case the user is (also) a seller. In case of a buyer this should be set to PAYER.
     *
     * Generated from protobuf field <code>.eftypay.payments.mangopay.UserCategory userCategory = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setUserCategory($var)
    {
        GPBUtil::checkEnum($var, \Eftypay\Payments\Mangopay\UserCategory::class);
        $this->userCategory = $var;

        return $this;
    }

    /**
     * userId is the Mangopay userId. This is a read only field, set by Efty Pay and only used internally.
     *
     * Generated from protobuf field <code>string userId = 3;</code>
     * @return string
     */
    public function getUserId()
    {
        return $this->userId;
    }

    /**
     * userId is the Mangopay userId. This is a read only field, set by Efty Pay and only used internally.
     *
     * Generated from protobuf field <code>string userId = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setUserId($var)
    {
        GPBUtil::checkString($var, True);
        $this->userId = $var;

        return $this;
    }

    /**
     * kycLevel contains the KYC level from Mangopay, only set for users of type OWNER. Readonly field set by Efty Pay.
     *
     * Generated from protobuf field <code>.eftypay.payments.mangopay.KycLevel kycLevel = 4;</code>
     * @return int
     */
    public function getKycLevel()
    {
        return $this->kycLevel;
    }

    /**
     * kycLevel contains the KYC level from Mangopay, only set for users of type OWNER. Readonly field set by Efty Pay.
     *
     * Generated from protobuf field <code>.eftypay.payments.mangopay.KycLevel kycLevel = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setKycLevel($var)
    {
        GPBUtil::checkEnum($var, \Eftypay\Payments\Mangopay\KycLevel::class);
        $this->kycLevel = $var;

        return $this;
    }

}

