<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: public/payments/mangopay/onboarding.proto

namespace Eftypay\Payments\Mangopay;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * MangopayOnboarding contains the information for onboarding a natural person or legal user with Mangopay.
 *
 * Generated from protobuf message <code>eftypay.payments.mangopay.MangopayOnboarding</code>
 */
class MangopayOnboarding extends \Google\Protobuf\Internal\Message
{
    /**
     * sellerUserId contains the ID of the seller user to create / update the onboarding for. The ID is a compressed 22 character UUID.
     *
     * Generated from protobuf field <code>.eftypay.common.Id sellerUserId = 1;</code>
     */
    protected $sellerUserId = null;
    /**
     * naturalUser contains the onboarding information and is only required if onboardingType is NATURAL_USER.
     *
     * Generated from protobuf field <code>.eftypay.payments.mangopay.Person naturalUser = 2;</code>
     */
    protected $naturalUser = null;
    /**
     * legalUser contains the onboarding information and is only required if onboardingType is LEGAL_USER.
     *
     * Generated from protobuf field <code>.eftypay.payments.mangopay.LegalUser legalUser = 3;</code>
     */
    protected $legalUser = null;
    /**
     * onboardingType is the type of onboarding request.
     *
     * Generated from protobuf field <code>.eftypay.payments.mangopay.OnboardingType onboardingType = 4;</code>
     */
    protected $onboardingType = 0;
    /**
     * kycLevel contains the KYC level from Mangopay. Readonly field set by Efty Pay.
     *
     * Generated from protobuf field <code>.eftypay.payments.mangopay.KycLevel kycLevel = 5;</code>
     */
    protected $kycLevel = 0;
    /**
     * associatedKycDocumentDetails contains details about the required KYC documents required for Mangopay user verification. Readonly field set by Efty Pay.
     *
     * Generated from protobuf field <code>repeated .eftypay.payments.mangopay.KycDocument associatedKycDocumentDetails = 6;</code>
     */
    private $associatedKycDocumentDetails;
    /**
     * onboardingAdditionalInformation contains additional onboarding information from Mangopay (i.e. reasons for re-uploading documents, providing additional information etc.). Readonly field set by Efty Pay.
     *
     * Generated from protobuf field <code>string onboardingAdditionalInformation = 7;</code>
     */
    protected $onboardingAdditionalInformation = '';
    /**
     * created is the timestamp the onboarding request was created. Readonly field set by Efty Pay.
     *
     * Generated from protobuf field <code>.google.protobuf.Timestamp created = 8;</code>
     */
    protected $created = null;
    /**
     * updated is the timestamp the onboarding request was updated. Readonly field set by Efty Pay.
     *
     * Generated from protobuf field <code>.google.protobuf.Timestamp updated = 9;</code>
     */
    protected $updated = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Eftypay\Common\Id $sellerUserId
     *           sellerUserId contains the ID of the seller user to create / update the onboarding for. The ID is a compressed 22 character UUID.
     *     @type \Eftypay\Payments\Mangopay\Person $naturalUser
     *           naturalUser contains the onboarding information and is only required if onboardingType is NATURAL_USER.
     *     @type \Eftypay\Payments\Mangopay\LegalUser $legalUser
     *           legalUser contains the onboarding information and is only required if onboardingType is LEGAL_USER.
     *     @type int $onboardingType
     *           onboardingType is the type of onboarding request.
     *     @type int $kycLevel
     *           kycLevel contains the KYC level from Mangopay. Readonly field set by Efty Pay.
     *     @type array<\Eftypay\Payments\Mangopay\KycDocument>|\Google\Protobuf\Internal\RepeatedField $associatedKycDocumentDetails
     *           associatedKycDocumentDetails contains details about the required KYC documents required for Mangopay user verification. Readonly field set by Efty Pay.
     *     @type string $onboardingAdditionalInformation
     *           onboardingAdditionalInformation contains additional onboarding information from Mangopay (i.e. reasons for re-uploading documents, providing additional information etc.). Readonly field set by Efty Pay.
     *     @type \Google\Protobuf\Timestamp $created
     *           created is the timestamp the onboarding request was created. Readonly field set by Efty Pay.
     *     @type \Google\Protobuf\Timestamp $updated
     *           updated is the timestamp the onboarding request was updated. Readonly field set by Efty Pay.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\PBPublic\Payments\Mangopay\Onboarding::initOnce();
        parent::__construct($data);
    }

    /**
     * sellerUserId contains the ID of the seller user to create / update the onboarding for. The ID is a compressed 22 character UUID.
     *
     * Generated from protobuf field <code>.eftypay.common.Id sellerUserId = 1;</code>
     * @return \Eftypay\Common\Id|null
     */
    public function getSellerUserId()
    {
        return $this->sellerUserId;
    }

    public function hasSellerUserId()
    {
        return isset($this->sellerUserId);
    }

    public function clearSellerUserId()
    {
        unset($this->sellerUserId);
    }

    /**
     * sellerUserId contains the ID of the seller user to create / update the onboarding for. The ID is a compressed 22 character UUID.
     *
     * Generated from protobuf field <code>.eftypay.common.Id sellerUserId = 1;</code>
     * @param \Eftypay\Common\Id $var
     * @return $this
     */
    public function setSellerUserId($var)
    {
        GPBUtil::checkMessage($var, \Eftypay\Common\Id::class);
        $this->sellerUserId = $var;

        return $this;
    }

    /**
     * naturalUser contains the onboarding information and is only required if onboardingType is NATURAL_USER.
     *
     * Generated from protobuf field <code>.eftypay.payments.mangopay.Person naturalUser = 2;</code>
     * @return \Eftypay\Payments\Mangopay\Person|null
     */
    public function getNaturalUser()
    {
        return $this->naturalUser;
    }

    public function hasNaturalUser()
    {
        return isset($this->naturalUser);
    }

    public function clearNaturalUser()
    {
        unset($this->naturalUser);
    }

    /**
     * naturalUser contains the onboarding information and is only required if onboardingType is NATURAL_USER.
     *
     * Generated from protobuf field <code>.eftypay.payments.mangopay.Person naturalUser = 2;</code>
     * @param \Eftypay\Payments\Mangopay\Person $var
     * @return $this
     */
    public function setNaturalUser($var)
    {
        GPBUtil::checkMessage($var, \Eftypay\Payments\Mangopay\Person::class);
        $this->naturalUser = $var;

        return $this;
    }

    /**
     * legalUser contains the onboarding information and is only required if onboardingType is LEGAL_USER.
     *
     * Generated from protobuf field <code>.eftypay.payments.mangopay.LegalUser legalUser = 3;</code>
     * @return \Eftypay\Payments\Mangopay\LegalUser|null
     */
    public function getLegalUser()
    {
        return $this->legalUser;
    }

    public function hasLegalUser()
    {
        return isset($this->legalUser);
    }

    public function clearLegalUser()
    {
        unset($this->legalUser);
    }

    /**
     * legalUser contains the onboarding information and is only required if onboardingType is LEGAL_USER.
     *
     * Generated from protobuf field <code>.eftypay.payments.mangopay.LegalUser legalUser = 3;</code>
     * @param \Eftypay\Payments\Mangopay\LegalUser $var
     * @return $this
     */
    public function setLegalUser($var)
    {
        GPBUtil::checkMessage($var, \Eftypay\Payments\Mangopay\LegalUser::class);
        $this->legalUser = $var;

        return $this;
    }

    /**
     * onboardingType is the type of onboarding request.
     *
     * Generated from protobuf field <code>.eftypay.payments.mangopay.OnboardingType onboardingType = 4;</code>
     * @return int
     */
    public function getOnboardingType()
    {
        return $this->onboardingType;
    }

    /**
     * onboardingType is the type of onboarding request.
     *
     * Generated from protobuf field <code>.eftypay.payments.mangopay.OnboardingType onboardingType = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setOnboardingType($var)
    {
        GPBUtil::checkEnum($var, \Eftypay\Payments\Mangopay\OnboardingType::class);
        $this->onboardingType = $var;

        return $this;
    }

    /**
     * kycLevel contains the KYC level from Mangopay. Readonly field set by Efty Pay.
     *
     * Generated from protobuf field <code>.eftypay.payments.mangopay.KycLevel kycLevel = 5;</code>
     * @return int
     */
    public function getKycLevel()
    {
        return $this->kycLevel;
    }

    /**
     * kycLevel contains the KYC level from Mangopay. Readonly field set by Efty Pay.
     *
     * Generated from protobuf field <code>.eftypay.payments.mangopay.KycLevel kycLevel = 5;</code>
     * @param int $var
     * @return $this
     */
    public function setKycLevel($var)
    {
        GPBUtil::checkEnum($var, \Eftypay\Payments\Mangopay\KycLevel::class);
        $this->kycLevel = $var;

        return $this;
    }

    /**
     * associatedKycDocumentDetails contains details about the required KYC documents required for Mangopay user verification. Readonly field set by Efty Pay.
     *
     * Generated from protobuf field <code>repeated .eftypay.payments.mangopay.KycDocument associatedKycDocumentDetails = 6;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getAssociatedKycDocumentDetails()
    {
        return $this->associatedKycDocumentDetails;
    }

    /**
     * associatedKycDocumentDetails contains details about the required KYC documents required for Mangopay user verification. Readonly field set by Efty Pay.
     *
     * Generated from protobuf field <code>repeated .eftypay.payments.mangopay.KycDocument associatedKycDocumentDetails = 6;</code>
     * @param array<\Eftypay\Payments\Mangopay\KycDocument>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setAssociatedKycDocumentDetails($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Eftypay\Payments\Mangopay\KycDocument::class);
        $this->associatedKycDocumentDetails = $arr;

        return $this;
    }

    /**
     * onboardingAdditionalInformation contains additional onboarding information from Mangopay (i.e. reasons for re-uploading documents, providing additional information etc.). Readonly field set by Efty Pay.
     *
     * Generated from protobuf field <code>string onboardingAdditionalInformation = 7;</code>
     * @return string
     */
    public function getOnboardingAdditionalInformation()
    {
        return $this->onboardingAdditionalInformation;
    }

    /**
     * onboardingAdditionalInformation contains additional onboarding information from Mangopay (i.e. reasons for re-uploading documents, providing additional information etc.). Readonly field set by Efty Pay.
     *
     * Generated from protobuf field <code>string onboardingAdditionalInformation = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setOnboardingAdditionalInformation($var)
    {
        GPBUtil::checkString($var, True);
        $this->onboardingAdditionalInformation = $var;

        return $this;
    }

    /**
     * created is the timestamp the onboarding request was created. Readonly field set by Efty Pay.
     *
     * Generated from protobuf field <code>.google.protobuf.Timestamp created = 8;</code>
     * @return \Google\Protobuf\Timestamp|null
     */
    public function getCreated()
    {
        return $this->created;
    }

    public function hasCreated()
    {
        return isset($this->created);
    }

    public function clearCreated()
    {
        unset($this->created);
    }

    /**
     * created is the timestamp the onboarding request was created. Readonly field set by Efty Pay.
     *
     * Generated from protobuf field <code>.google.protobuf.Timestamp created = 8;</code>
     * @param \Google\Protobuf\Timestamp $var
     * @return $this
     */
    public function setCreated($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Timestamp::class);
        $this->created = $var;

        return $this;
    }

    /**
     * updated is the timestamp the onboarding request was updated. Readonly field set by Efty Pay.
     *
     * Generated from protobuf field <code>.google.protobuf.Timestamp updated = 9;</code>
     * @return \Google\Protobuf\Timestamp|null
     */
    public function getUpdated()
    {
        return $this->updated;
    }

    public function hasUpdated()
    {
        return isset($this->updated);
    }

    public function clearUpdated()
    {
        unset($this->updated);
    }

    /**
     * updated is the timestamp the onboarding request was updated. Readonly field set by Efty Pay.
     *
     * Generated from protobuf field <code>.google.protobuf.Timestamp updated = 9;</code>
     * @param \Google\Protobuf\Timestamp $var
     * @return $this
     */
    public function setUpdated($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Timestamp::class);
        $this->updated = $var;

        return $this;
    }

}

