<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: public/payments/mangopay/onboarding.proto

namespace Eftypay\Payments\Mangopay;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Person contains details about a person for Mangopay onboarding.
 *
 * Generated from protobuf message <code>eftypay.payments.mangopay.Person</code>
 */
class Person extends \Google\Protobuf\Internal\Message
{
    /**
     * firstName contains the first name of the person.
     *
     * Generated from protobuf field <code>string firstName = 1;</code>
     */
    protected $firstName = '';
    /**
     * lastName contains the last name of the person.
     *
     * Generated from protobuf field <code>string lastName = 2;</code>
     */
    protected $lastName = '';
    /**
     * email contains the email of the person.
     *
     * Generated from protobuf field <code>string email = 3;</code>
     */
    protected $email = '';
    /**
     * dateOfBirth is the Date of Birth of the person.
     *
     * Generated from protobuf field <code>.google.protobuf.Timestamp dateOfBirth = 4;</code>
     */
    protected $dateOfBirth = null;
    /**
     * nationality contains the nationality of the user in the ISO 3166-1 alpha-2 format: https://mangopay.com/docs/api-basics/data-formats
     *
     * Generated from protobuf field <code>.eftypay.common.CountryCode nationality = 5;</code>
     */
    protected $nationality = 0;
    /**
     * countryOfResidence contains the country of residence of the person in the ISO 3166-1 alpha-2 format: https://mangopay.com/docs/api-basics/data-formats
     *
     * Generated from protobuf field <code>.eftypay.common.CountryCode countryOfResidence = 6;</code>
     */
    protected $countryOfResidence = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $firstName
     *           firstName contains the first name of the person.
     *     @type string $lastName
     *           lastName contains the last name of the person.
     *     @type string $email
     *           email contains the email of the person.
     *     @type \Google\Protobuf\Timestamp $dateOfBirth
     *           dateOfBirth is the Date of Birth of the person.
     *     @type int $nationality
     *           nationality contains the nationality of the user in the ISO 3166-1 alpha-2 format: https://mangopay.com/docs/api-basics/data-formats
     *     @type int $countryOfResidence
     *           countryOfResidence contains the country of residence of the person in the ISO 3166-1 alpha-2 format: https://mangopay.com/docs/api-basics/data-formats
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\PBPublic\Payments\Mangopay\Onboarding::initOnce();
        parent::__construct($data);
    }

    /**
     * firstName contains the first name of the person.
     *
     * Generated from protobuf field <code>string firstName = 1;</code>
     * @return string
     */
    public function getFirstName()
    {
        return $this->firstName;
    }

    /**
     * firstName contains the first name of the person.
     *
     * Generated from protobuf field <code>string firstName = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setFirstName($var)
    {
        GPBUtil::checkString($var, True);
        $this->firstName = $var;

        return $this;
    }

    /**
     * lastName contains the last name of the person.
     *
     * Generated from protobuf field <code>string lastName = 2;</code>
     * @return string
     */
    public function getLastName()
    {
        return $this->lastName;
    }

    /**
     * lastName contains the last name of the person.
     *
     * Generated from protobuf field <code>string lastName = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setLastName($var)
    {
        GPBUtil::checkString($var, True);
        $this->lastName = $var;

        return $this;
    }

    /**
     * email contains the email of the person.
     *
     * Generated from protobuf field <code>string email = 3;</code>
     * @return string
     */
    public function getEmail()
    {
        return $this->email;
    }

    /**
     * email contains the email of the person.
     *
     * Generated from protobuf field <code>string email = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setEmail($var)
    {
        GPBUtil::checkString($var, True);
        $this->email = $var;

        return $this;
    }

    /**
     * dateOfBirth is the Date of Birth of the person.
     *
     * Generated from protobuf field <code>.google.protobuf.Timestamp dateOfBirth = 4;</code>
     * @return \Google\Protobuf\Timestamp|null
     */
    public function getDateOfBirth()
    {
        return $this->dateOfBirth;
    }

    public function hasDateOfBirth()
    {
        return isset($this->dateOfBirth);
    }

    public function clearDateOfBirth()
    {
        unset($this->dateOfBirth);
    }

    /**
     * dateOfBirth is the Date of Birth of the person.
     *
     * Generated from protobuf field <code>.google.protobuf.Timestamp dateOfBirth = 4;</code>
     * @param \Google\Protobuf\Timestamp $var
     * @return $this
     */
    public function setDateOfBirth($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Timestamp::class);
        $this->dateOfBirth = $var;

        return $this;
    }

    /**
     * nationality contains the nationality of the user in the ISO 3166-1 alpha-2 format: https://mangopay.com/docs/api-basics/data-formats
     *
     * Generated from protobuf field <code>.eftypay.common.CountryCode nationality = 5;</code>
     * @return int
     */
    public function getNationality()
    {
        return $this->nationality;
    }

    /**
     * nationality contains the nationality of the user in the ISO 3166-1 alpha-2 format: https://mangopay.com/docs/api-basics/data-formats
     *
     * Generated from protobuf field <code>.eftypay.common.CountryCode nationality = 5;</code>
     * @param int $var
     * @return $this
     */
    public function setNationality($var)
    {
        GPBUtil::checkEnum($var, \Eftypay\Common\CountryCode::class);
        $this->nationality = $var;

        return $this;
    }

    /**
     * countryOfResidence contains the country of residence of the person in the ISO 3166-1 alpha-2 format: https://mangopay.com/docs/api-basics/data-formats
     *
     * Generated from protobuf field <code>.eftypay.common.CountryCode countryOfResidence = 6;</code>
     * @return int
     */
    public function getCountryOfResidence()
    {
        return $this->countryOfResidence;
    }

    /**
     * countryOfResidence contains the country of residence of the person in the ISO 3166-1 alpha-2 format: https://mangopay.com/docs/api-basics/data-formats
     *
     * Generated from protobuf field <code>.eftypay.common.CountryCode countryOfResidence = 6;</code>
     * @param int $var
     * @return $this
     */
    public function setCountryOfResidence($var)
    {
        GPBUtil::checkEnum($var, \Eftypay\Common\CountryCode::class);
        $this->countryOfResidence = $var;

        return $this;
    }

}

