<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: public/payments/mangopay/onboarding.proto

namespace Eftypay\Payments\Mangopay;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * UboDeclaration contains information about an UBO declaration.
 *
 * Generated from protobuf message <code>eftypay.payments.mangopay.UboDeclaration</code>
 */
class UboDeclaration extends \Google\Protobuf\Internal\Message
{
    /**
     * mangopayUboDeclarationId is set by Efty Pay, is readonly, and contains the Mangopay UBO declaration ID.
     *
     * Generated from protobuf field <code>string mangopayUboDeclarationId = 1;</code>
     */
    protected $mangopayUboDeclarationId = '';
    /**
     * beneficialOwners contains the details of all the benficial owners of the company that own 25% or more.
     *
     * Generated from protobuf field <code>repeated .eftypay.payments.mangopay.Ubo beneficialOwners = 2;</code>
     */
    private $beneficialOwners;
    /**
     * status the review status of the UBO declaration, can be: CREATED, VALIDATION_ASKED, INCOMPLETE, VALIDATED, REFUSED. The field is readonly and set by Efty Pay.
     *
     * Generated from protobuf field <code>string status = 3;</code>
     */
    protected $status = '';
    /**
     * refusedReason is only set if STATUS = REFUSED or INCOMPLETE and contains the refused reason from Mangopay.
     *
     * Generated from protobuf field <code>string refusedReason = 5;</code>
     */
    protected $refusedReason = '';
    /**
     * refusedReasonMessage is only set if STATUS = REFUSED or INCOMPLETE and contains additional information about why the UBO Declaration was refused or marked as incomplete, provided by Mangopay’s team.
     *
     * Generated from protobuf field <code>string refusedReasonMessage = 6;</code>
     */
    protected $refusedReasonMessage = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $mangopayUboDeclarationId
     *           mangopayUboDeclarationId is set by Efty Pay, is readonly, and contains the Mangopay UBO declaration ID.
     *     @type array<\Eftypay\Payments\Mangopay\Ubo>|\Google\Protobuf\Internal\RepeatedField $beneficialOwners
     *           beneficialOwners contains the details of all the benficial owners of the company that own 25% or more.
     *     @type string $status
     *           status the review status of the UBO declaration, can be: CREATED, VALIDATION_ASKED, INCOMPLETE, VALIDATED, REFUSED. The field is readonly and set by Efty Pay.
     *     @type string $refusedReason
     *           refusedReason is only set if STATUS = REFUSED or INCOMPLETE and contains the refused reason from Mangopay.
     *     @type string $refusedReasonMessage
     *           refusedReasonMessage is only set if STATUS = REFUSED or INCOMPLETE and contains additional information about why the UBO Declaration was refused or marked as incomplete, provided by Mangopay’s team.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\PBPublic\Payments\Mangopay\Onboarding::initOnce();
        parent::__construct($data);
    }

    /**
     * mangopayUboDeclarationId is set by Efty Pay, is readonly, and contains the Mangopay UBO declaration ID.
     *
     * Generated from protobuf field <code>string mangopayUboDeclarationId = 1;</code>
     * @return string
     */
    public function getMangopayUboDeclarationId()
    {
        return $this->mangopayUboDeclarationId;
    }

    /**
     * mangopayUboDeclarationId is set by Efty Pay, is readonly, and contains the Mangopay UBO declaration ID.
     *
     * Generated from protobuf field <code>string mangopayUboDeclarationId = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setMangopayUboDeclarationId($var)
    {
        GPBUtil::checkString($var, True);
        $this->mangopayUboDeclarationId = $var;

        return $this;
    }

    /**
     * beneficialOwners contains the details of all the benficial owners of the company that own 25% or more.
     *
     * Generated from protobuf field <code>repeated .eftypay.payments.mangopay.Ubo beneficialOwners = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getBeneficialOwners()
    {
        return $this->beneficialOwners;
    }

    /**
     * beneficialOwners contains the details of all the benficial owners of the company that own 25% or more.
     *
     * Generated from protobuf field <code>repeated .eftypay.payments.mangopay.Ubo beneficialOwners = 2;</code>
     * @param array<\Eftypay\Payments\Mangopay\Ubo>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setBeneficialOwners($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Eftypay\Payments\Mangopay\Ubo::class);
        $this->beneficialOwners = $arr;

        return $this;
    }

    /**
     * status the review status of the UBO declaration, can be: CREATED, VALIDATION_ASKED, INCOMPLETE, VALIDATED, REFUSED. The field is readonly and set by Efty Pay.
     *
     * Generated from protobuf field <code>string status = 3;</code>
     * @return string
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     * status the review status of the UBO declaration, can be: CREATED, VALIDATION_ASKED, INCOMPLETE, VALIDATED, REFUSED. The field is readonly and set by Efty Pay.
     *
     * Generated from protobuf field <code>string status = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setStatus($var)
    {
        GPBUtil::checkString($var, True);
        $this->status = $var;

        return $this;
    }

    /**
     * refusedReason is only set if STATUS = REFUSED or INCOMPLETE and contains the refused reason from Mangopay.
     *
     * Generated from protobuf field <code>string refusedReason = 5;</code>
     * @return string
     */
    public function getRefusedReason()
    {
        return $this->refusedReason;
    }

    /**
     * refusedReason is only set if STATUS = REFUSED or INCOMPLETE and contains the refused reason from Mangopay.
     *
     * Generated from protobuf field <code>string refusedReason = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setRefusedReason($var)
    {
        GPBUtil::checkString($var, True);
        $this->refusedReason = $var;

        return $this;
    }

    /**
     * refusedReasonMessage is only set if STATUS = REFUSED or INCOMPLETE and contains additional information about why the UBO Declaration was refused or marked as incomplete, provided by Mangopay’s team.
     *
     * Generated from protobuf field <code>string refusedReasonMessage = 6;</code>
     * @return string
     */
    public function getRefusedReasonMessage()
    {
        return $this->refusedReasonMessage;
    }

    /**
     * refusedReasonMessage is only set if STATUS = REFUSED or INCOMPLETE and contains additional information about why the UBO Declaration was refused or marked as incomplete, provided by Mangopay’s team.
     *
     * Generated from protobuf field <code>string refusedReasonMessage = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setRefusedReasonMessage($var)
    {
        GPBUtil::checkString($var, True);
        $this->refusedReasonMessage = $var;

        return $this;
    }

}

