<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: public/payments/mangopay/mangopay.proto

namespace Eftypay\Payments\Mangopay;

use UnexpectedValueException;

/**
 * UserCategory contains the Mangopay user category. All sellers needs to be created as OWNER user.
 *
 * Protobuf type <code>eftypay.payments.mangopay.UserCategory</code>
 */
class UserCategory
{
    /**
     * USER_TYPE_NONE is the default user category (which is zero and not transmitted on the wire).
     *
     * Generated from protobuf enum <code>USER_TYPE_NONE = 0;</code>
     */
    const USER_TYPE_NONE = 0;
    /**
     * PAYER is a Mangopay User who can only make pay-ins to their wallet and transfers to other wallets.
     *
     * Generated from protobuf enum <code>PAYER = 1;</code>
     */
    const PAYER = 1;
    /**
     * OWNER is a Mangopay user who can do everything a Payer can, plus receive transfers to their wallet. To request payouts, an OWNER user must be verified through the Mangopay KYC process.
     *
     * Generated from protobuf enum <code>OWNER = 2;</code>
     */
    const OWNER = 2;

    private static $valueToName = [
        self::USER_TYPE_NONE => 'USER_TYPE_NONE',
        self::PAYER => 'PAYER',
        self::OWNER => 'OWNER',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

