<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: public/transactions/activity/activity.proto

namespace Eftypay\Transactions\Activity;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * GetStatusChangeConfigResponse is returned by the GetStatusChangeConfiguration endpoint.
 *
 * Generated from protobuf message <code>eftypay.transactions.activity.GetStatusChangeConfigurationResponse</code>
 */
class GetStatusChangeConfigurationResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .eftypay.transactions.activity.StatusChangeConfig statusChangeConfiguration = 1;</code>
     */
    private $statusChangeConfiguration;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type array<\Eftypay\Transactions\Activity\StatusChangeConfig>|\Google\Protobuf\Internal\RepeatedField $statusChangeConfiguration
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\PBPublic\Transactions\Activity\Activity::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .eftypay.transactions.activity.StatusChangeConfig statusChangeConfiguration = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getStatusChangeConfiguration()
    {
        return $this->statusChangeConfiguration;
    }

    /**
     * Generated from protobuf field <code>repeated .eftypay.transactions.activity.StatusChangeConfig statusChangeConfiguration = 1;</code>
     * @param array<\Eftypay\Transactions\Activity\StatusChangeConfig>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setStatusChangeConfiguration($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Eftypay\Transactions\Activity\StatusChangeConfig::class);
        $this->statusChangeConfiguration = $arr;

        return $this;
    }

}

