<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: public/transactions/activity/activity.proto

namespace Eftypay\Transactions\Activity;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * SendEmailNotificationConfig is used to configure when we send email notifications to notify a party that they have a new in-app message.
 *
 * Generated from protobuf message <code>eftypay.transactions.activity.SendEmailNotificationConfig</code>
 */
class SendEmailNotificationConfig extends \Google\Protobuf\Internal\Message
{
    /**
     * omitEmailNotificationBuyerIfSourceIsBin if set to true sends message notification to the Buyer for BIN sourced transactions.
     *
     * Generated from protobuf field <code>bool omitEmailNotificationBuyerIfSourceIsBin = 1;</code>
     */
    protected $omitEmailNotificationBuyerIfSourceIsBin = false;
    /**
     * omitEmailNotificationBuyerIfSourceIsNotBin if set to true sends message notification to the Buyer for non-BIN sourced transactions.
     *
     * Generated from protobuf field <code>bool omitEmailNotificationBuyerIfSourceIsNotBin = 2;</code>
     */
    protected $omitEmailNotificationBuyerIfSourceIsNotBin = false;
    /**
     * omitEmailNotificationSellerIfSourceIsBin if set to true sends message notification to the Seller for BIN sourced transactions.
     *
     * Generated from protobuf field <code>bool omitEmailNotificationSellerIfSourceIsBin = 3;</code>
     */
    protected $omitEmailNotificationSellerIfSourceIsBin = false;
    /**
     * omitEmailNotificationSellerIfSourceIsNotBin if set to true sends message notification to the Seller for non-BIN sourced transactions.
     *
     * Generated from protobuf field <code>bool omitEmailNotificationSellerIfSourceIsNotBin = 4;</code>
     */
    protected $omitEmailNotificationSellerIfSourceIsNotBin = false;
    /**
     * omitEmailNotificationAdminIfSourceIsBin if set to true sends message notification to the Admin for BIN sourced transactions.
     *
     * Generated from protobuf field <code>bool omitEmailNotificationAdminIfSourceIsBin = 5;</code>
     */
    protected $omitEmailNotificationAdminIfSourceIsBin = false;
    /**
     * omitEmailNotificationAdminIfSourceIsNotBin if set to true sends message notification to the Admin for non-BIN sourced transactions.
     *
     * Generated from protobuf field <code>bool omitEmailNotificationAdminIfSourceIsNotBin = 6;</code>
     */
    protected $omitEmailNotificationAdminIfSourceIsNotBin = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type bool $omitEmailNotificationBuyerIfSourceIsBin
     *           omitEmailNotificationBuyerIfSourceIsBin if set to true sends message notification to the Buyer for BIN sourced transactions.
     *     @type bool $omitEmailNotificationBuyerIfSourceIsNotBin
     *           omitEmailNotificationBuyerIfSourceIsNotBin if set to true sends message notification to the Buyer for non-BIN sourced transactions.
     *     @type bool $omitEmailNotificationSellerIfSourceIsBin
     *           omitEmailNotificationSellerIfSourceIsBin if set to true sends message notification to the Seller for BIN sourced transactions.
     *     @type bool $omitEmailNotificationSellerIfSourceIsNotBin
     *           omitEmailNotificationSellerIfSourceIsNotBin if set to true sends message notification to the Seller for non-BIN sourced transactions.
     *     @type bool $omitEmailNotificationAdminIfSourceIsBin
     *           omitEmailNotificationAdminIfSourceIsBin if set to true sends message notification to the Admin for BIN sourced transactions.
     *     @type bool $omitEmailNotificationAdminIfSourceIsNotBin
     *           omitEmailNotificationAdminIfSourceIsNotBin if set to true sends message notification to the Admin for non-BIN sourced transactions.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\PBPublic\Transactions\Activity\Activity::initOnce();
        parent::__construct($data);
    }

    /**
     * omitEmailNotificationBuyerIfSourceIsBin if set to true sends message notification to the Buyer for BIN sourced transactions.
     *
     * Generated from protobuf field <code>bool omitEmailNotificationBuyerIfSourceIsBin = 1;</code>
     * @return bool
     */
    public function getOmitEmailNotificationBuyerIfSourceIsBin()
    {
        return $this->omitEmailNotificationBuyerIfSourceIsBin;
    }

    /**
     * omitEmailNotificationBuyerIfSourceIsBin if set to true sends message notification to the Buyer for BIN sourced transactions.
     *
     * Generated from protobuf field <code>bool omitEmailNotificationBuyerIfSourceIsBin = 1;</code>
     * @param bool $var
     * @return $this
     */
    public function setOmitEmailNotificationBuyerIfSourceIsBin($var)
    {
        GPBUtil::checkBool($var);
        $this->omitEmailNotificationBuyerIfSourceIsBin = $var;

        return $this;
    }

    /**
     * omitEmailNotificationBuyerIfSourceIsNotBin if set to true sends message notification to the Buyer for non-BIN sourced transactions.
     *
     * Generated from protobuf field <code>bool omitEmailNotificationBuyerIfSourceIsNotBin = 2;</code>
     * @return bool
     */
    public function getOmitEmailNotificationBuyerIfSourceIsNotBin()
    {
        return $this->omitEmailNotificationBuyerIfSourceIsNotBin;
    }

    /**
     * omitEmailNotificationBuyerIfSourceIsNotBin if set to true sends message notification to the Buyer for non-BIN sourced transactions.
     *
     * Generated from protobuf field <code>bool omitEmailNotificationBuyerIfSourceIsNotBin = 2;</code>
     * @param bool $var
     * @return $this
     */
    public function setOmitEmailNotificationBuyerIfSourceIsNotBin($var)
    {
        GPBUtil::checkBool($var);
        $this->omitEmailNotificationBuyerIfSourceIsNotBin = $var;

        return $this;
    }

    /**
     * omitEmailNotificationSellerIfSourceIsBin if set to true sends message notification to the Seller for BIN sourced transactions.
     *
     * Generated from protobuf field <code>bool omitEmailNotificationSellerIfSourceIsBin = 3;</code>
     * @return bool
     */
    public function getOmitEmailNotificationSellerIfSourceIsBin()
    {
        return $this->omitEmailNotificationSellerIfSourceIsBin;
    }

    /**
     * omitEmailNotificationSellerIfSourceIsBin if set to true sends message notification to the Seller for BIN sourced transactions.
     *
     * Generated from protobuf field <code>bool omitEmailNotificationSellerIfSourceIsBin = 3;</code>
     * @param bool $var
     * @return $this
     */
    public function setOmitEmailNotificationSellerIfSourceIsBin($var)
    {
        GPBUtil::checkBool($var);
        $this->omitEmailNotificationSellerIfSourceIsBin = $var;

        return $this;
    }

    /**
     * omitEmailNotificationSellerIfSourceIsNotBin if set to true sends message notification to the Seller for non-BIN sourced transactions.
     *
     * Generated from protobuf field <code>bool omitEmailNotificationSellerIfSourceIsNotBin = 4;</code>
     * @return bool
     */
    public function getOmitEmailNotificationSellerIfSourceIsNotBin()
    {
        return $this->omitEmailNotificationSellerIfSourceIsNotBin;
    }

    /**
     * omitEmailNotificationSellerIfSourceIsNotBin if set to true sends message notification to the Seller for non-BIN sourced transactions.
     *
     * Generated from protobuf field <code>bool omitEmailNotificationSellerIfSourceIsNotBin = 4;</code>
     * @param bool $var
     * @return $this
     */
    public function setOmitEmailNotificationSellerIfSourceIsNotBin($var)
    {
        GPBUtil::checkBool($var);
        $this->omitEmailNotificationSellerIfSourceIsNotBin = $var;

        return $this;
    }

    /**
     * omitEmailNotificationAdminIfSourceIsBin if set to true sends message notification to the Admin for BIN sourced transactions.
     *
     * Generated from protobuf field <code>bool omitEmailNotificationAdminIfSourceIsBin = 5;</code>
     * @return bool
     */
    public function getOmitEmailNotificationAdminIfSourceIsBin()
    {
        return $this->omitEmailNotificationAdminIfSourceIsBin;
    }

    /**
     * omitEmailNotificationAdminIfSourceIsBin if set to true sends message notification to the Admin for BIN sourced transactions.
     *
     * Generated from protobuf field <code>bool omitEmailNotificationAdminIfSourceIsBin = 5;</code>
     * @param bool $var
     * @return $this
     */
    public function setOmitEmailNotificationAdminIfSourceIsBin($var)
    {
        GPBUtil::checkBool($var);
        $this->omitEmailNotificationAdminIfSourceIsBin = $var;

        return $this;
    }

    /**
     * omitEmailNotificationAdminIfSourceIsNotBin if set to true sends message notification to the Admin for non-BIN sourced transactions.
     *
     * Generated from protobuf field <code>bool omitEmailNotificationAdminIfSourceIsNotBin = 6;</code>
     * @return bool
     */
    public function getOmitEmailNotificationAdminIfSourceIsNotBin()
    {
        return $this->omitEmailNotificationAdminIfSourceIsNotBin;
    }

    /**
     * omitEmailNotificationAdminIfSourceIsNotBin if set to true sends message notification to the Admin for non-BIN sourced transactions.
     *
     * Generated from protobuf field <code>bool omitEmailNotificationAdminIfSourceIsNotBin = 6;</code>
     * @param bool $var
     * @return $this
     */
    public function setOmitEmailNotificationAdminIfSourceIsNotBin($var)
    {
        GPBUtil::checkBool($var);
        $this->omitEmailNotificationAdminIfSourceIsNotBin = $var;

        return $this;
    }

}

