<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: public/transactions/activity/activity.proto

namespace Eftypay\Transactions\Activity;

use UnexpectedValueException;

/**
 * TransactionSubStatus represents a sub-status for the main-status. A transaction status will always have one of the 3 sub-statuses associated with it.
 * TransactionStatus & TransactionSubStatus combined tell the current status of the transaction.
 *
 * Protobuf type <code>eftypay.transactions.activity.TransactionSubStatus</code>
 */
class TransactionSubStatus
{
    /**
     * SUB_STATUS_NONE is the default sub-status of a transaction (which is zero and not transmitted on the wire).
     *
     * Generated from protobuf enum <code>SUB_STATUS_NONE = 0;</code>
     */
    const SUB_STATUS_NONE = 0;
    /**
     * INITIATED_OR_REQUESTED means the main status was initiated or request.
     *
     * Generated from protobuf enum <code>INITIATED_OR_REQUESTED = 1;</code>
     */
    const INITIATED_OR_REQUESTED = 1;
    /**
     * CONFIRMED means the main status was confirmed by an Efty Pay admin.
     *
     * Generated from protobuf enum <code>CONFIRMED = 2;</code>
     */
    const CONFIRMED = 2;
    /**
     * APPROVED means the main status was approved by a second Efty Pay admin.
     *
     * Generated from protobuf enum <code>APPROVED = 3;</code>
     */
    const APPROVED = 3;

    private static $valueToName = [
        self::SUB_STATUS_NONE => 'SUB_STATUS_NONE',
        self::INITIATED_OR_REQUESTED => 'INITIATED_OR_REQUESTED',
        self::CONFIRMED => 'CONFIRMED',
        self::APPROVED => 'APPROVED',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

