<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: public/transactions/activity/activity.proto

namespace Eftypay\Transactions\Activity;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * TransactionStatusConfiguration holds information about the status configuration:
 * - How long a transaction can be in a status & sub-status.
 * - Notification information when a transaction enters the status, and when it leaves the status (for buyer, seller, admin).
 *
 * Generated from protobuf message <code>eftypay.transactions.activity.TransactionStatusConfiguration</code>
 */
class TransactionStatusConfiguration extends \Google\Protobuf\Internal\Message
{
    /**
     * status contains the main transaction status this configuration is for.
     *
     * Generated from protobuf field <code>.eftypay.transactions.activity.TransactionStatus status = 1;</code>
     */
    protected $status = 0;
    /**
     * subStatus contains the sub-status this configuration is for.
     *
     * Generated from protobuf field <code>.eftypay.transactions.activity.TransactionSubStatus subStatus = 2;</code>
     */
    protected $subStatus = 0;
    /**
     * sendNotificationOnEnteringStatus indicates if an in-app notification needs to be sent when a transaction transitions into this status & sub-status.
     *
     * Generated from protobuf field <code>bool sendNotificationOnEnteringStatus = 3;</code>
     */
    protected $sendNotificationOnEnteringStatus = false;
    /**
     * notificationReceiversOnEntering indicates which parties related to the transaction will receive notifications when a transaction enters the status & sub-status.
     *
     * Generated from protobuf field <code>repeated .eftypay.transactions.activity.TransactionParty notificationReceiversOnEntering = 5;</code>
     */
    private $notificationReceiversOnEntering;
    /**
     * notificationReceiversOnExiting indicates which parties related to the transaction will receive notifications when a transaction exits the status & sub-status.
     *
     * Generated from protobuf field <code>repeated .eftypay.transactions.activity.TransactionParty notificationReceiversOnExiting = 6;</code>
     */
    private $notificationReceiversOnExiting;
    /**
     * notificationContents contains the contents of the notification for the different receiving parties.
     *
     * Generated from protobuf field <code>.eftypay.transactions.activity.NotificationContents notificationContents = 7;</code>
     */
    protected $notificationContents = null;
    /**
     * maxStatusDurationInDays indicates how many days a transaction can be in this status, before a reminder is sent to the status owner to take action.
     *
     * Generated from protobuf field <code>int32 maxStatusDurationInDays = 8;</code>
     */
    protected $maxStatusDurationInDays = 0;
    /**
     * sendEmailNotificationConfig contains the settings if email notifications need to be sent on status changes.
     *
     * Generated from protobuf field <code>.eftypay.transactions.activity.SendEmailNotificationConfig sendEmailNotificationConfig = 10;</code>
     */
    protected $sendEmailNotificationConfig = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $status
     *           status contains the main transaction status this configuration is for.
     *     @type int $subStatus
     *           subStatus contains the sub-status this configuration is for.
     *     @type bool $sendNotificationOnEnteringStatus
     *           sendNotificationOnEnteringStatus indicates if an in-app notification needs to be sent when a transaction transitions into this status & sub-status.
     *     @type array<int>|\Google\Protobuf\Internal\RepeatedField $notificationReceiversOnEntering
     *           notificationReceiversOnEntering indicates which parties related to the transaction will receive notifications when a transaction enters the status & sub-status.
     *     @type array<int>|\Google\Protobuf\Internal\RepeatedField $notificationReceiversOnExiting
     *           notificationReceiversOnExiting indicates which parties related to the transaction will receive notifications when a transaction exits the status & sub-status.
     *     @type \Eftypay\Transactions\Activity\NotificationContents $notificationContents
     *           notificationContents contains the contents of the notification for the different receiving parties.
     *     @type int $maxStatusDurationInDays
     *           maxStatusDurationInDays indicates how many days a transaction can be in this status, before a reminder is sent to the status owner to take action.
     *     @type \Eftypay\Transactions\Activity\SendEmailNotificationConfig $sendEmailNotificationConfig
     *           sendEmailNotificationConfig contains the settings if email notifications need to be sent on status changes.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\PBPublic\Transactions\Activity\Activity::initOnce();
        parent::__construct($data);
    }

    /**
     * status contains the main transaction status this configuration is for.
     *
     * Generated from protobuf field <code>.eftypay.transactions.activity.TransactionStatus status = 1;</code>
     * @return int
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     * status contains the main transaction status this configuration is for.
     *
     * Generated from protobuf field <code>.eftypay.transactions.activity.TransactionStatus status = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setStatus($var)
    {
        GPBUtil::checkEnum($var, \Eftypay\Transactions\Activity\TransactionStatus::class);
        $this->status = $var;

        return $this;
    }

    /**
     * subStatus contains the sub-status this configuration is for.
     *
     * Generated from protobuf field <code>.eftypay.transactions.activity.TransactionSubStatus subStatus = 2;</code>
     * @return int
     */
    public function getSubStatus()
    {
        return $this->subStatus;
    }

    /**
     * subStatus contains the sub-status this configuration is for.
     *
     * Generated from protobuf field <code>.eftypay.transactions.activity.TransactionSubStatus subStatus = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setSubStatus($var)
    {
        GPBUtil::checkEnum($var, \Eftypay\Transactions\Activity\TransactionSubStatus::class);
        $this->subStatus = $var;

        return $this;
    }

    /**
     * sendNotificationOnEnteringStatus indicates if an in-app notification needs to be sent when a transaction transitions into this status & sub-status.
     *
     * Generated from protobuf field <code>bool sendNotificationOnEnteringStatus = 3;</code>
     * @return bool
     */
    public function getSendNotificationOnEnteringStatus()
    {
        return $this->sendNotificationOnEnteringStatus;
    }

    /**
     * sendNotificationOnEnteringStatus indicates if an in-app notification needs to be sent when a transaction transitions into this status & sub-status.
     *
     * Generated from protobuf field <code>bool sendNotificationOnEnteringStatus = 3;</code>
     * @param bool $var
     * @return $this
     */
    public function setSendNotificationOnEnteringStatus($var)
    {
        GPBUtil::checkBool($var);
        $this->sendNotificationOnEnteringStatus = $var;

        return $this;
    }

    /**
     * notificationReceiversOnEntering indicates which parties related to the transaction will receive notifications when a transaction enters the status & sub-status.
     *
     * Generated from protobuf field <code>repeated .eftypay.transactions.activity.TransactionParty notificationReceiversOnEntering = 5;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getNotificationReceiversOnEntering()
    {
        return $this->notificationReceiversOnEntering;
    }

    /**
     * notificationReceiversOnEntering indicates which parties related to the transaction will receive notifications when a transaction enters the status & sub-status.
     *
     * Generated from protobuf field <code>repeated .eftypay.transactions.activity.TransactionParty notificationReceiversOnEntering = 5;</code>
     * @param array<int>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setNotificationReceiversOnEntering($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::ENUM, \Eftypay\Transactions\Activity\TransactionParty::class);
        $this->notificationReceiversOnEntering = $arr;

        return $this;
    }

    /**
     * notificationReceiversOnExiting indicates which parties related to the transaction will receive notifications when a transaction exits the status & sub-status.
     *
     * Generated from protobuf field <code>repeated .eftypay.transactions.activity.TransactionParty notificationReceiversOnExiting = 6;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getNotificationReceiversOnExiting()
    {
        return $this->notificationReceiversOnExiting;
    }

    /**
     * notificationReceiversOnExiting indicates which parties related to the transaction will receive notifications when a transaction exits the status & sub-status.
     *
     * Generated from protobuf field <code>repeated .eftypay.transactions.activity.TransactionParty notificationReceiversOnExiting = 6;</code>
     * @param array<int>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setNotificationReceiversOnExiting($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::ENUM, \Eftypay\Transactions\Activity\TransactionParty::class);
        $this->notificationReceiversOnExiting = $arr;

        return $this;
    }

    /**
     * notificationContents contains the contents of the notification for the different receiving parties.
     *
     * Generated from protobuf field <code>.eftypay.transactions.activity.NotificationContents notificationContents = 7;</code>
     * @return \Eftypay\Transactions\Activity\NotificationContents|null
     */
    public function getNotificationContents()
    {
        return $this->notificationContents;
    }

    public function hasNotificationContents()
    {
        return isset($this->notificationContents);
    }

    public function clearNotificationContents()
    {
        unset($this->notificationContents);
    }

    /**
     * notificationContents contains the contents of the notification for the different receiving parties.
     *
     * Generated from protobuf field <code>.eftypay.transactions.activity.NotificationContents notificationContents = 7;</code>
     * @param \Eftypay\Transactions\Activity\NotificationContents $var
     * @return $this
     */
    public function setNotificationContents($var)
    {
        GPBUtil::checkMessage($var, \Eftypay\Transactions\Activity\NotificationContents::class);
        $this->notificationContents = $var;

        return $this;
    }

    /**
     * maxStatusDurationInDays indicates how many days a transaction can be in this status, before a reminder is sent to the status owner to take action.
     *
     * Generated from protobuf field <code>int32 maxStatusDurationInDays = 8;</code>
     * @return int
     */
    public function getMaxStatusDurationInDays()
    {
        return $this->maxStatusDurationInDays;
    }

    /**
     * maxStatusDurationInDays indicates how many days a transaction can be in this status, before a reminder is sent to the status owner to take action.
     *
     * Generated from protobuf field <code>int32 maxStatusDurationInDays = 8;</code>
     * @param int $var
     * @return $this
     */
    public function setMaxStatusDurationInDays($var)
    {
        GPBUtil::checkInt32($var);
        $this->maxStatusDurationInDays = $var;

        return $this;
    }

    /**
     * sendEmailNotificationConfig contains the settings if email notifications need to be sent on status changes.
     *
     * Generated from protobuf field <code>.eftypay.transactions.activity.SendEmailNotificationConfig sendEmailNotificationConfig = 10;</code>
     * @return \Eftypay\Transactions\Activity\SendEmailNotificationConfig|null
     */
    public function getSendEmailNotificationConfig()
    {
        return $this->sendEmailNotificationConfig;
    }

    public function hasSendEmailNotificationConfig()
    {
        return isset($this->sendEmailNotificationConfig);
    }

    public function clearSendEmailNotificationConfig()
    {
        unset($this->sendEmailNotificationConfig);
    }

    /**
     * sendEmailNotificationConfig contains the settings if email notifications need to be sent on status changes.
     *
     * Generated from protobuf field <code>.eftypay.transactions.activity.SendEmailNotificationConfig sendEmailNotificationConfig = 10;</code>
     * @param \Eftypay\Transactions\Activity\SendEmailNotificationConfig $var
     * @return $this
     */
    public function setSendEmailNotificationConfig($var)
    {
        GPBUtil::checkMessage($var, \Eftypay\Transactions\Activity\SendEmailNotificationConfig::class);
        $this->sendEmailNotificationConfig = $var;

        return $this;
    }

}

