<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: public/payments/payment.proto

namespace GPBMetadata\PBPublic\Payments;

class Payment
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\PBPublic\Payments\Mangopay\Mangopay::initOnce();
        $pool->internalAddGeneratedFile(
            '
Å
public/payments/payment.protoeftypay.payments"U
PaymentDetailsC
mangopayDetails (2*.eftypay.payments.mangopay.MangopayDetails"s
CheckoutDetails
checkoutUrl (	K
mangopayDetails (22.eftypay.payments.mangopay.MangopayCheckoutDetailsB>Z<bitbucket.org/eftypay/efty-pay-models/sdk/go/public/paymentsbproto3'
        , true);

        static::$is_initialized = true;
    }
}

