<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: public/integrators/integrator.proto

namespace GPBMetadata\PBPublic\Integrators;

class Integrator
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
¨
#public/integrators/integrator.protoeftypay.integrators" 
CommissionSettings
eftyPayFlatFeeAmount (#
eftyPayCommissionPercentage (
integratorFlatFeeAmount (&
integratorCommissionPercentage (BAZ?bitbucket.org/eftypay/efty-pay-models/sdk/go/public/integratorsbproto3'
        , true);

        static::$is_initialized = true;
    }
}

