<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: public/messages/message.proto

namespace Eftypay\Messages;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * File describes a file for uploading. Files are stored in a CDN.
 *
 * Generated from protobuf message <code>eftypay.messages.File</code>
 */
class File extends \Google\Protobuf\Internal\Message
{
    /**
     * name is the name of the file.
     *
     * Generated from protobuf field <code>string name = 1;</code>
     */
    protected $name = '';
    /**
     * contents is the file contents as a base64 encoded string.
     *
     * Generated from protobuf field <code>string contents = 2;</code>
     */
    protected $contents = '';
    /**
     * fileType is the type of the file.
     *
     * Generated from protobuf field <code>.eftypay.messages.FileType fileType = 3;</code>
     */
    protected $fileType = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $name
     *           name is the name of the file.
     *     @type string $contents
     *           contents is the file contents as a base64 encoded string.
     *     @type int $fileType
     *           fileType is the type of the file.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\PBPublic\Messages\Message::initOnce();
        parent::__construct($data);
    }

    /**
     * name is the name of the file.
     *
     * Generated from protobuf field <code>string name = 1;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * name is the name of the file.
     *
     * Generated from protobuf field <code>string name = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

    /**
     * contents is the file contents as a base64 encoded string.
     *
     * Generated from protobuf field <code>string contents = 2;</code>
     * @return string
     */
    public function getContents()
    {
        return $this->contents;
    }

    /**
     * contents is the file contents as a base64 encoded string.
     *
     * Generated from protobuf field <code>string contents = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setContents($var)
    {
        GPBUtil::checkString($var, True);
        $this->contents = $var;

        return $this;
    }

    /**
     * fileType is the type of the file.
     *
     * Generated from protobuf field <code>.eftypay.messages.FileType fileType = 3;</code>
     * @return int
     */
    public function getFileType()
    {
        return $this->fileType;
    }

    /**
     * fileType is the type of the file.
     *
     * Generated from protobuf field <code>.eftypay.messages.FileType fileType = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setFileType($var)
    {
        GPBUtil::checkEnum($var, \Eftypay\Messages\FileType::class);
        $this->fileType = $var;

        return $this;
    }

}

