<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: public/messages/message.proto

namespace Eftypay\Messages;

use UnexpectedValueException;

/**
 * Protobuf type <code>eftypay.messages.FileType</code>
 */
class FileType
{
    /**
     * FILE_TYPE_NONE is the default file type (which is zero and not transmitted on the wire).
     *
     * Generated from protobuf enum <code>FILE_TYPE_NONE = 0;</code>
     */
    const FILE_TYPE_NONE = 0;
    /**
     * IMAGE means the attachment is an image; supported image types are PNG, JPG & GIF.
     *
     * Generated from protobuf enum <code>IMAGE = 1;</code>
     */
    const IMAGE = 1;
    /**
     * PDF means the attachment is a PDF.
     *
     * Generated from protobuf enum <code>PDF = 2;</code>
     */
    const PDF = 2;

    private static $valueToName = [
        self::FILE_TYPE_NONE => 'FILE_TYPE_NONE',
        self::IMAGE => 'IMAGE',
        self::PDF => 'PDF',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

