<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: public/messages/message.proto

namespace Eftypay\Messages;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Message is an individual message, that is sent by either the buyer, seller or admin, or system generated.
 * If a message contains images or videos, then these are uploaded individually to a CDN first, and inserted as a link in the message contents (this is to keep the message objects small).
 * Messages can be autogenerated by the system, or manually typed by a seller, buyer or admin.
 * Messages are immutable.
 *
 * Generated from protobuf message <code>eftypay.messages.Message</code>
 */
class Message extends \Google\Protobuf\Internal\Message
{
    /**
     * id is unique ID of the message. The ID is a compressed 22 character UUID. The ID is autogenerated.
     *
     * Generated from protobuf field <code>string id = 1;</code>
     */
    protected $id = '';
    /**
     * author is the author / sender of the message. In case of a system generated message, this field will contain the integrator admin user, and the isSystemGeneratedMessage will be true.
     *
     * Generated from protobuf field <code>.eftypay.users.User author = 2;</code>
     */
    protected $author = null;
    /**
     * receiver is the receiver of the message (this can also be the integrator admin).
     *
     * Generated from protobuf field <code>.eftypay.users.User receiver = 3;</code>
     */
    protected $receiver = null;
    /**
     * contents is the text contents of the message (and can include CDN links to images, videos). When the front-end detects these links, it can choose to render a preview.
     *
     * Generated from protobuf field <code>string contents = 4;</code>
     */
    protected $contents = '';
    /**
     * isSystemGeneratedMessage indicates if this is a system generated message.
     *
     * Generated from protobuf field <code>bool isSystemGeneratedMessage = 5;</code>
     */
    protected $isSystemGeneratedMessage = false;
    /**
     * transactionActivity indicates this message was automatically generated by a change to the transaction (this is an optional field).
     *
     * Generated from protobuf field <code>.eftypay.transactions.activity.TransactionActivity transactionActivity = 6;</code>
     */
    protected $transactionActivity = null;
    /**
     * date is the date the message was sent.
     *
     * Generated from protobuf field <code>.google.protobuf.Timestamp date = 7;</code>
     */
    protected $date = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $id
     *           id is unique ID of the message. The ID is a compressed 22 character UUID. The ID is autogenerated.
     *     @type \Eftypay\Users\User $author
     *           author is the author / sender of the message. In case of a system generated message, this field will contain the integrator admin user, and the isSystemGeneratedMessage will be true.
     *     @type \Eftypay\Users\User $receiver
     *           receiver is the receiver of the message (this can also be the integrator admin).
     *     @type string $contents
     *           contents is the text contents of the message (and can include CDN links to images, videos). When the front-end detects these links, it can choose to render a preview.
     *     @type bool $isSystemGeneratedMessage
     *           isSystemGeneratedMessage indicates if this is a system generated message.
     *     @type \Eftypay\Transactions\Activity\TransactionActivity $transactionActivity
     *           transactionActivity indicates this message was automatically generated by a change to the transaction (this is an optional field).
     *     @type \Google\Protobuf\Timestamp $date
     *           date is the date the message was sent.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\PBPublic\Messages\Message::initOnce();
        parent::__construct($data);
    }

    /**
     * id is unique ID of the message. The ID is a compressed 22 character UUID. The ID is autogenerated.
     *
     * Generated from protobuf field <code>string id = 1;</code>
     * @return string
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * id is unique ID of the message. The ID is a compressed 22 character UUID. The ID is autogenerated.
     *
     * Generated from protobuf field <code>string id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkString($var, True);
        $this->id = $var;

        return $this;
    }

    /**
     * author is the author / sender of the message. In case of a system generated message, this field will contain the integrator admin user, and the isSystemGeneratedMessage will be true.
     *
     * Generated from protobuf field <code>.eftypay.users.User author = 2;</code>
     * @return \Eftypay\Users\User|null
     */
    public function getAuthor()
    {
        return $this->author;
    }

    public function hasAuthor()
    {
        return isset($this->author);
    }

    public function clearAuthor()
    {
        unset($this->author);
    }

    /**
     * author is the author / sender of the message. In case of a system generated message, this field will contain the integrator admin user, and the isSystemGeneratedMessage will be true.
     *
     * Generated from protobuf field <code>.eftypay.users.User author = 2;</code>
     * @param \Eftypay\Users\User $var
     * @return $this
     */
    public function setAuthor($var)
    {
        GPBUtil::checkMessage($var, \Eftypay\Users\User::class);
        $this->author = $var;

        return $this;
    }

    /**
     * receiver is the receiver of the message (this can also be the integrator admin).
     *
     * Generated from protobuf field <code>.eftypay.users.User receiver = 3;</code>
     * @return \Eftypay\Users\User|null
     */
    public function getReceiver()
    {
        return $this->receiver;
    }

    public function hasReceiver()
    {
        return isset($this->receiver);
    }

    public function clearReceiver()
    {
        unset($this->receiver);
    }

    /**
     * receiver is the receiver of the message (this can also be the integrator admin).
     *
     * Generated from protobuf field <code>.eftypay.users.User receiver = 3;</code>
     * @param \Eftypay\Users\User $var
     * @return $this
     */
    public function setReceiver($var)
    {
        GPBUtil::checkMessage($var, \Eftypay\Users\User::class);
        $this->receiver = $var;

        return $this;
    }

    /**
     * contents is the text contents of the message (and can include CDN links to images, videos). When the front-end detects these links, it can choose to render a preview.
     *
     * Generated from protobuf field <code>string contents = 4;</code>
     * @return string
     */
    public function getContents()
    {
        return $this->contents;
    }

    /**
     * contents is the text contents of the message (and can include CDN links to images, videos). When the front-end detects these links, it can choose to render a preview.
     *
     * Generated from protobuf field <code>string contents = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setContents($var)
    {
        GPBUtil::checkString($var, True);
        $this->contents = $var;

        return $this;
    }

    /**
     * isSystemGeneratedMessage indicates if this is a system generated message.
     *
     * Generated from protobuf field <code>bool isSystemGeneratedMessage = 5;</code>
     * @return bool
     */
    public function getIsSystemGeneratedMessage()
    {
        return $this->isSystemGeneratedMessage;
    }

    /**
     * isSystemGeneratedMessage indicates if this is a system generated message.
     *
     * Generated from protobuf field <code>bool isSystemGeneratedMessage = 5;</code>
     * @param bool $var
     * @return $this
     */
    public function setIsSystemGeneratedMessage($var)
    {
        GPBUtil::checkBool($var);
        $this->isSystemGeneratedMessage = $var;

        return $this;
    }

    /**
     * transactionActivity indicates this message was automatically generated by a change to the transaction (this is an optional field).
     *
     * Generated from protobuf field <code>.eftypay.transactions.activity.TransactionActivity transactionActivity = 6;</code>
     * @return \Eftypay\Transactions\Activity\TransactionActivity|null
     */
    public function getTransactionActivity()
    {
        return $this->transactionActivity;
    }

    public function hasTransactionActivity()
    {
        return isset($this->transactionActivity);
    }

    public function clearTransactionActivity()
    {
        unset($this->transactionActivity);
    }

    /**
     * transactionActivity indicates this message was automatically generated by a change to the transaction (this is an optional field).
     *
     * Generated from protobuf field <code>.eftypay.transactions.activity.TransactionActivity transactionActivity = 6;</code>
     * @param \Eftypay\Transactions\Activity\TransactionActivity $var
     * @return $this
     */
    public function setTransactionActivity($var)
    {
        GPBUtil::checkMessage($var, \Eftypay\Transactions\Activity\TransactionActivity::class);
        $this->transactionActivity = $var;

        return $this;
    }

    /**
     * date is the date the message was sent.
     *
     * Generated from protobuf field <code>.google.protobuf.Timestamp date = 7;</code>
     * @return \Google\Protobuf\Timestamp|null
     */
    public function getDate()
    {
        return $this->date;
    }

    public function hasDate()
    {
        return isset($this->date);
    }

    public function clearDate()
    {
        unset($this->date);
    }

    /**
     * date is the date the message was sent.
     *
     * Generated from protobuf field <code>.google.protobuf.Timestamp date = 7;</code>
     * @param \Google\Protobuf\Timestamp $var
     * @return $this
     */
    public function setDate($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Timestamp::class);
        $this->date = $var;

        return $this;
    }

}

