<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: public/messages/message.proto

namespace Eftypay\Messages;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * SendMessageRequest contains the details to send a message for a transaction (if the API is used). System generated messages are automatically added to a transaction.
 *
 * Generated from protobuf message <code>eftypay.messages.SendMessageRequest</code>
 */
class SendMessageRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * transactionId refers to the transaction this message relates to.
     *
     * Generated from protobuf field <code>string transactionId = 1;</code>
     */
    protected $transactionId = '';
    /**
     * authorId refers to the user ID of the author of the message. Required field.
     *
     * Generated from protobuf field <code>string authorId = 2;</code>
     */
    protected $authorId = '';
    /**
     * receiverId refers to the user ID of the receiver of the message. If left blank, will be set to the Efty Pay admin.
     *
     * Generated from protobuf field <code>string receiverId = 3;</code>
     */
    protected $receiverId = '';
    /**
     * integratorId is an optional field to indicate the integrator data-space. Can only be set by admin.
     *
     * Generated from protobuf field <code>string integratorId = 6;</code>
     */
    protected $integratorId = '';
    /**
     * omitMessageNotificationEmail if set to true will only send the message to the receiver, and no notification email.
     *
     * Generated from protobuf field <code>bool omitMessageNotificationEmail = 7;</code>
     */
    protected $omitMessageNotificationEmail = false;
    protected $contents;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $transactionId
     *           transactionId refers to the transaction this message relates to.
     *     @type string $authorId
     *           authorId refers to the user ID of the author of the message. Required field.
     *     @type string $receiverId
     *           receiverId refers to the user ID of the receiver of the message. If left blank, will be set to the Efty Pay admin.
     *     @type string $message
     *           messages contains the text for the message.
     *     @type \Eftypay\Messages\File $file
     *           file contains the file for uploading.
     *     @type string $integratorId
     *           integratorId is an optional field to indicate the integrator data-space. Can only be set by admin.
     *     @type bool $omitMessageNotificationEmail
     *           omitMessageNotificationEmail if set to true will only send the message to the receiver, and no notification email.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\PBPublic\Messages\Message::initOnce();
        parent::__construct($data);
    }

    /**
     * transactionId refers to the transaction this message relates to.
     *
     * Generated from protobuf field <code>string transactionId = 1;</code>
     * @return string
     */
    public function getTransactionId()
    {
        return $this->transactionId;
    }

    /**
     * transactionId refers to the transaction this message relates to.
     *
     * Generated from protobuf field <code>string transactionId = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setTransactionId($var)
    {
        GPBUtil::checkString($var, True);
        $this->transactionId = $var;

        return $this;
    }

    /**
     * authorId refers to the user ID of the author of the message. Required field.
     *
     * Generated from protobuf field <code>string authorId = 2;</code>
     * @return string
     */
    public function getAuthorId()
    {
        return $this->authorId;
    }

    /**
     * authorId refers to the user ID of the author of the message. Required field.
     *
     * Generated from protobuf field <code>string authorId = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setAuthorId($var)
    {
        GPBUtil::checkString($var, True);
        $this->authorId = $var;

        return $this;
    }

    /**
     * receiverId refers to the user ID of the receiver of the message. If left blank, will be set to the Efty Pay admin.
     *
     * Generated from protobuf field <code>string receiverId = 3;</code>
     * @return string
     */
    public function getReceiverId()
    {
        return $this->receiverId;
    }

    /**
     * receiverId refers to the user ID of the receiver of the message. If left blank, will be set to the Efty Pay admin.
     *
     * Generated from protobuf field <code>string receiverId = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setReceiverId($var)
    {
        GPBUtil::checkString($var, True);
        $this->receiverId = $var;

        return $this;
    }

    /**
     * messages contains the text for the message.
     *
     * Generated from protobuf field <code>string message = 4;</code>
     * @return string
     */
    public function getMessage()
    {
        return $this->readOneof(4);
    }

    public function hasMessage()
    {
        return $this->hasOneof(4);
    }

    /**
     * messages contains the text for the message.
     *
     * Generated from protobuf field <code>string message = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setMessage($var)
    {
        GPBUtil::checkString($var, True);
        $this->writeOneof(4, $var);

        return $this;
    }

    /**
     * file contains the file for uploading.
     *
     * Generated from protobuf field <code>.eftypay.messages.File file = 5;</code>
     * @return \Eftypay\Messages\File|null
     */
    public function getFile()
    {
        return $this->readOneof(5);
    }

    public function hasFile()
    {
        return $this->hasOneof(5);
    }

    /**
     * file contains the file for uploading.
     *
     * Generated from protobuf field <code>.eftypay.messages.File file = 5;</code>
     * @param \Eftypay\Messages\File $var
     * @return $this
     */
    public function setFile($var)
    {
        GPBUtil::checkMessage($var, \Eftypay\Messages\File::class);
        $this->writeOneof(5, $var);

        return $this;
    }

    /**
     * integratorId is an optional field to indicate the integrator data-space. Can only be set by admin.
     *
     * Generated from protobuf field <code>string integratorId = 6;</code>
     * @return string
     */
    public function getIntegratorId()
    {
        return $this->integratorId;
    }

    /**
     * integratorId is an optional field to indicate the integrator data-space. Can only be set by admin.
     *
     * Generated from protobuf field <code>string integratorId = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setIntegratorId($var)
    {
        GPBUtil::checkString($var, True);
        $this->integratorId = $var;

        return $this;
    }

    /**
     * omitMessageNotificationEmail if set to true will only send the message to the receiver, and no notification email.
     *
     * Generated from protobuf field <code>bool omitMessageNotificationEmail = 7;</code>
     * @return bool
     */
    public function getOmitMessageNotificationEmail()
    {
        return $this->omitMessageNotificationEmail;
    }

    /**
     * omitMessageNotificationEmail if set to true will only send the message to the receiver, and no notification email.
     *
     * Generated from protobuf field <code>bool omitMessageNotificationEmail = 7;</code>
     * @param bool $var
     * @return $this
     */
    public function setOmitMessageNotificationEmail($var)
    {
        GPBUtil::checkBool($var);
        $this->omitMessageNotificationEmail = $var;

        return $this;
    }

    /**
     * @return string
     */
    public function getContents()
    {
        return $this->whichOneof("contents");
    }

}

